### ISSUE TITLE
No usable Pokestops

### ISSUE THREAD

**Issue by clavin99** [NECROBOTIO/NecroBot#2659] opened 2016-08-03 20:28 UTC
This has just started appearing when I tried to launch the bot. Last used the bot around 6 hours ago with no app use in between.

**Comment by somani6** [comment] 2016-08-03 20:28
It seems like Niantic changed the way they provide MapObjects. We are working on a fix as FeroxRev is offline right now.

**Comment by shottothedome** [comment] 2016-08-03 20:29
ok great. Ran into the same issue just now too when logging in

**Comment by somani6** [comment] 2016-08-03 20:30
just don't use the bot until a patch will be released.

**Comment by wowstin** [comment] 2016-08-03 20:30
I have faith in the devs here lol I bet it'll be fixed in no time :3

**Comment by BuluBulu27** [comment] 2016-08-03 20:30
Since the PokeStops are not working, we can't snipe with this bot anymore, can we?

**Comment by somani6** [comment] 2016-08-03 20:30
this issue is pretty deep, so it might take as long as it takes :)

**Comment by clavin99** [comment] 2016-08-03 20:31
Thanks for the update.

**Comment by nfettinger** [comment] 2016-08-03 20:32
Duplicate of #2645

**Comment by elmaarmut** [comment] 2016-08-03 20:32
I think there is an IP ban in place. I logged in from my phone with my home Wifi and used an incense, pokemon ran after 1st pokeball. I reconnected with my 4.5G, and I was able to catch the 2nd pokemon from the incense.

I'd say leave the bot alone for now and let the pros handle it. I think they are trying to block external devices that send high number of inquiries to the server.

**Closed by nfettinger** 2016-08-03 20:32 UTC
