### ISSUE TITLE
[FeatureRequest] Relate KeepPokemonsThatCanEvolve with PokemonsToEvolve

### ISSUE THREAD

**Issue by heArt-coder** [NECROBOTIO/NecroBot#2034] opened 2016-08-02 11:42 UTC
KeepPokemonsThatCanEvolve is really handy for maximizing Lucky egg usuage but it is not perfect rightnow and needs a lot of manuel handling to get max xp out of it.

In short it only needs to hold Pokemons that is on PokemonsToEvolve list

In long: bot keeps 150~/350 pokemons on normal work and when i get new lucky eggs i'm turning KeepPokemonsThatCanEvolve : True and it starts to hold and gets pokemon storage full in 1-2 hours
And here is the problem... Some of these pokemons are not logical to evolve for xp (magicarp, squirtle, charmander ect) so bot keeps around 70~(i have put almost every pokemon on my evolve list to get this down to 70 or it doesnt even gets 50 evolveble pokemons to make lucky egg configs work) pokemons that will endup transfered without evolving...

I could add magicarp, squirtle, charmander ect or even non-evolving pokemons to ignore list but its very bad for a lot of reasons.

Rightnow in order to get max xp out of lucky eggs i need to keep checking bots, change configs, clean pokemons manually and got around 80 evolve xp...

Making it only holding pokemons on PokemonsToEvolve list could make lucky egg configs useable, keep it all in auto (no config changes or manual cleaning) and get +180~k xp in 1-2 hours...

Thanks for all the good work and sory for long read ;)

**Comment by redChrillz** [comment] 2016-08-02 11:45
I have a pull-req for this here,
https://github.com/NECROBOTIO/NecroBot/pull/2031

**Comment by actislav** [comment] 2016-08-02 20:12
EvolveKeptPokemonsAtStorageUsagePercentage all is what you need set it to 100%(but i am not recommend 100 exactly 95 is safer) and you will get maximum power :) (and of course KeepPokemonsThatCanEvolve  = true)

**Comment by heArt-coder** [comment] 2016-08-02 21:19
But i dont want it to hold magicarps, dratinis etc... Only pokemons that i added to PokemonsToEvolve list... Isn't it simple?

**Comment by nfettinger** [comment] 2016-08-03 13:09
Duplicate of #2001

**Closed by nfettinger** 2016-08-03 13:09 UTC
Labels: enhancement, ready
