### ISSUE TITLE
bot version output is cached. please state somewhere the bots actual version

### ISSUE THREAD

**Issue by Marsinator** [NECROBOTIO/NecroBot#2222] opened 2016-08-02 20:17 UTC
[22:12] Mars: people get confused by the congratz youre running 0.5 message. now I know its cached. but can we put the actual version they have somewhere?
[22:13] Mars: like at the top of the config or something?
[22:13] Mars: I wouldnt put it in the actual necrobot file name

**Comment by recon88** [comment] 2016-08-02 20:20
Duplicate of #2218 :D

**Closed** 2016-08-02 20:20 UTC
Labels: enhancement
