### ISSUE TITLE
[bug] cant connect

### ISSUE THREAD

**Issue by Adriskye** [NECROBOTIO/NecroBot#2648] opened 2016-08-03 20:02 UTC
![necro](https://cloud.githubusercontent.com/assets/20812795/17380145/fbd81776-59c5-11e6-8d17-be92a714b2cf.png)

**Comment by Epinikion** [comment] 2016-08-03 20:03
same for me

**Comment by theloser** [comment] 2016-08-03 20:03
Niantic server may be down or Niantic changed something. All my four bots stopped working. Just calm down and chill...

**Comment by zionism** [comment] 2016-08-03 20:03
same, just started when downloaded the recent update for necro bot.  was working before update.

**Comment by nfettinger** [comment] 2016-08-03 20:03
Duplicate of #2645

**Comment by chezchelios** [comment] 2016-08-03 20:04
Cant connect even with nox...possible banwave?

**Closed** 2016-08-03 20:03 UTC
