### ISSUE TITLE
Bot transfered almost all pokemons

### ISSUE THREAD

**Issue by Rashk999** [NECROBOTIO/NecroBot#3944] opened 2016-08-09 16:37 UTC
After new update my bot transfered almost all of my pokemons .... here is list

[18:26:01] Rattata     	- CP:  365  IV:  71,60%   [Best CP:  365  IV:  71,60%] (Candies: 475)
[18:26:02] Wartortle   	- CP:  856  IV:  23,32%   [Best CP:  856  IV:  23,32%] (Candies: 27)
[18:26:03] Squirtle    	- CP:  502  IV:  24,73%   [Best CP:  502  IV:  24,73%] (Candies: 28)
[18:26:04] Shellder    	- CP:  475  IV:  68,45%   [Best CP:  475  IV:  68,45%] (Candies: 40)
[18:26:05] Pidgeotto   	- CP:  665  IV:  33,71%   [Best CP:  665  IV:  33,71%] (Candies: 1130)
[18:26:05] Mankey      	- CP:  256  IV:  69,66%   [Best CP:  256  IV:  69,66%] (Candies: 12)
[18:26:06] NidoranMale 	- CP:  418  IV:  13,05%   [Best CP:  418  IV:  13,05%] (Candies: 52)
[18:26:07] Parasect    	- CP:  978  IV:  88,27%   [Best CP:  978  IV:  88,27%] (Candies: 67)
[18:26:08] Pidgey      	- CP:  376  IV:  40,78%   [Best CP:  376  IV:  40,78%] (Candies: 1131)
[18:26:09] Magnemite   	- CP:  383  IV:  77,40%   [Best CP:  383  IV:  77,40%] (Candies: 35)
[18:26:10] Gloom       	- CP:  985  IV:  14,66%   [Best CP:  985  IV:  14,66%] (Candies: 24)
[18:26:11] Weedle      	- CP:   93  IV:  17,07%   [Best CP:   93  IV:  17,07%] (Candies: 402)
[18:26:11] Haunter     	- CP:  875  IV:  62,04%   [Best CP:  875  IV:  62,04%] (Candies: 71)
[18:26:12] Poliwhirl   	- CP:  741  IV:  38,28%   [Best CP:  741  IV:  38,28%] (Candies: 32)
[18:26:13] Ivysaur     	- CP:  914  IV:  88,89%   [Best CP:  914  IV:  88,89%] (Candies: 5)
[18:26:14] Growlithe   	- CP:  744  IV:  87,76%   [Best CP:  744  IV:  87,76%] (Candies: 23)
[18:26:15] Diglett     	- CP:  125  IV:  89,12%   [Best CP:  125  IV:  89,12%] (Candies: 20)
[18:26:16] Kabuto      	- CP:  450  IV:  78,49%   [Best CP:  450  IV:  78,49%] (Candies: 4)
[18:26:17] Zubat       	- CP:  377  IV:  61,57%   [Best CP:  377  IV:  61,57%] (Candies: 450)
[18:26:18] Seel        	- CP:  586  IV:  89,14%   [Best CP:  586  IV:  89,14%] (Candies: 32)
[18:26:19] Pikachu     	- CP:  349  IV:  42,46%   [Best CP:  349  IV:  42,46%] (Candies: 14)
[18:26:20] Tentacool   	- CP:  261  IV:  65,27%   [Best CP:  261  IV:  65,27%] (Candies: 12)
[18:26:20] Nidorina    	- CP:  546  IV:  51,46%   [Best CP:  546  IV:  51,46%] (Candies: 55)
[18:26:21] Slowpoke    	- CP:  678  IV:  87,30%   [Best CP:  678  IV:  87,30%] (Candies: 84)
[18:26:22] Pidgeot     	- CP: 1201  IV:  45,37%   [Best CP: 1201  IV:  45,37%] (Candies: 1132)
[18:26:23] Metapod     	- CP:  245  IV:  22,01%   [Best CP:  245  IV:  22,01%] (Candies: 45)
[18:26:24] Sandshrew   	- CP:  150  IV:  86,56%   [Best CP:  150  IV:  86,56%] (Candies: 22)
[18:26:26] Geodude     	- CP:  320  IV:  76,44%   [Best CP:  320  IV:  76,44%] (Candies: 26)
[18:26:27] Ekans       	- CP:  413  IV:  51,16%   [Best CP:  413  IV:  51,16%] (Candies: 28)
[18:26:28] Ponyta      	- CP:  667  IV:  80,31%   [Best CP:  667  IV:  80,31%] (Candies: 30)
[18:26:29] Jigglypuff  	- CP:  434  IV:  33,04%   [Best CP:  434  IV:  33,04%] (Candies: 21)
[18:26:30] Goldeen     	- CP:  318  IV:  51,33%   [Best CP:  318  IV:  51,33%] (Candies: 13)
[18:26:31] Raticate    	- CP:  876  IV:  59,67%   [Best CP:  876  IV:  59,67%] (Candies: 476)
[18:26:31] Machop      	- CP:  606  IV:  87,98%   [Best CP:  606  IV:  87,98%] (Candies: 22)
[18:26:32] Golbat      	- CP: 1183  IV:  87,95%   [Best CP: 1183  IV:  87,95%] (Candies: 451)
[18:26:33] Dragonair   	- CP:  967  IV:  81,69%   [Best CP:  967  IV:  81,69%] (Candies: 12)
[18:26:34] Meowth      	- CP:  472  IV:  80,84%   [Best CP:  472  IV:  80,84%] (Candies: 36)
[18:26:35] Fearow      	- CP: 1112  IV:  82,36%   [Best CP: 1112  IV:  82,36%] (Candies: 503)
[18:26:36] Slowbro     	- CP: 1232  IV:  45,27%   [Best CP: 1232  IV:  45,27%] (Candies: 85)
[18:26:36] Koffing     	- CP:  629  IV:  79,73%   [Best CP:  629  IV:  79,73%] (Candies: 32)
[18:26:37] Wigglytuff  	- CP: 1192  IV:  74,31%   [Best CP: 1192  IV:  74,31%] (Candies: 22)
[18:26:38] Bulbasaur   	- CP:  381  IV:  22,60%   [Best CP:  381  IV:  22,60%] (Candies: 6)
[18:26:39] Gastly      	- CP:  459  IV:  49,41%   [Best CP:  459  IV:  49,41%] (Candies: 72)
[18:26:40] Voltorb     	- CP:  454  IV:  78,52%   [Best CP:  454  IV:  78,52%] (Candies: 28)
[18:26:41] Seadra      	- CP:  166  IV:  60,36%   [Best CP:  166  IV:  60,36%] (Candies: 39)
[18:26:42] Venomoth    	- CP: 1029  IV:  71,62%   [Best CP: 1029  IV:  71,62%] (Candies: 18)
[18:26:43] NidoranFemale	- CP:  537  IV:  55,34%   [Best CP:  537  IV:  55,34%] (Candies: 56)
[18:26:44] Kakuna      	- CP:  202  IV:  26,51%   [Best CP:  202  IV:  26,51%] (Candies: 403)
[18:26:44] Abra        	- CP:  202  IV:  46,62%   [Best CP:  202  IV:  46,62%] (Candies: 42)
[18:26:45] Beedrill    	- CP:  829  IV:  55,83%   [Best CP:  829  IV:  55,83%] (Candies: 404)
[18:26:46] Caterpie    	- CP:  222  IV:  18,07%   [Best CP:  222  IV:  18,07%] (Candies: 46)

and here is actual config

{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": true,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 48.145507,
  "DefaultLongitude": 17.128784,
  "WalkingSpeedInKilometerPerHour": 18.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 500,
  "DelayBetweenPokemonCatch": 100,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  **"KeepMinDuplicatePokemon": 0,**
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.005,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 25000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "TotalAmountOfPokeballsToKeep": 160,
  "TotalAmountOfPotionsToKeep": 90,
  "TotalAmountOfRevivesToKeep": 40,
  "TotalAmountOfBerriesToKeep": 60,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [

i think its made by thick line, but im not a coder

**Comment by polypalm** [comment] 2016-08-09 16:39
same

**Comment by loneable** [comment] 2016-08-09 16:39
yea same its been doing this with the last few updates it keeps transferring all pokemon i wish they would fix it or tell us whats wrong

**Comment by Rashk999** [comment] 2016-08-09 16:40
one time it transfered drowzee which was 830CP and said that 350 is max so the bot kept 350 and transfered 830

**Comment by loneable** [comment] 2016-08-09 16:41
yea that y i been doing it on a whole new acc intill they fix it

**Comment by ONslaughTT** [comment] 2016-08-09 16:41
man i lost a lot of good pokemons... shit

**Comment by JTBomb007** [comment] 2016-08-09 16:41
Sorry I've not replied about this, as it happened to me a view versions ago and I just changed 

"KeepMinDuplicatePokemon": 0,

to

"KeepMinDuplicatePokemon": 1,

And it seems to be fine now.

Although I've not looked to see if I have two of everything. (Even if I do, better than 0)

**Comment by loneable** [comment] 2016-08-09 16:42
ok but i looked for that in the config and i could not find that in the newest bot

**Comment by iPollox** [comment] 2016-08-09 16:43
"KeepMinCp": 1250, <-- didnt see a single pokemon higher than this number on that list
"KeepMinDuplicatePokemon": 0, <-- deleted all that are under that CP because you dont want duplicates, if this was on it would leave 1 of each kind being the strongest CP wise

**Comment by buettner123** [comment] 2016-08-09 16:43
@Rashk999 this is probably related to the setting `"PrioritizeIvOverCp": true,`. I think that the Drowzee with the 350 CP value had an better IV Value.

**Comment by Rashk999** [comment] 2016-08-09 16:45
@buettner123 it was on false

**Comment by nfettinger** [comment] 2016-08-09 16:49
Please use the Discord chat rooms for general help.
There is a known issue, closing duplicate of #3338

**Closed by nfettinger** 2016-08-09 16:49 UTC
