### ISSUE TITLE
Spam With Favourite

### ISSUE THREAD

**Issue by dzik87** [NECROBOTIO/NecroBot#2125] opened 2016-08-02 17:39 UTC
Latest update keep spamming favorited message even it meant to be fixed.

**Comment by recon88** [comment] 2016-08-02 17:39
Duplicate of #1763

**Comment by dzik87** [comment] 2016-08-02 17:40
How it is duplicate if update was just released ?

**Closed by recon88** 2016-08-02 17:39 UTC

**Comment by recon88** [comment] 2016-08-02 17:50
Check the other ticket. It's the same issue and it is NOT closed yet. Therefore, issue not fixed.
