### ISSUE TITLE
[Improvement] Modify altitude for future usage!

### ISSUE THREAD

**Issue by Kalanhar** [NECROBOTIO/NecroBot#2691] opened 2016-08-03 21:33 UTC
First off i am not a programmer, i can understand a few of the lines but i am unable to script or anything like that.

I was thinking about a few of the possibilities and something came up in my mind!
One of the most important variables for the bot to work are the coords, but a neglected one by many is **Altitude** which many leave as **0**, that being See level +-2.
Now, i for one have used in the 2-3 places that i botted on, a medium altitude of the zone, i always taught that that specific argument should be filled.

As i see it:
- Phones **GPS** usually give out **Altitude** as well, meaning that Niantic may track that too (A few GPS maps give out altitude and the correction, to keep you in the right spot on the 3D map)
- The bot uses always the same altitude regardless of the actual zone.
- Is not that hard (as i see it) to set the altitude for each nest, poke stop and so on if Niantic wants to.
- I am not sure how the bot works, but i can assume, it knows from the API the coords for each poke stop after which it simulates a walking path twards that zone.

As my conspiracy theory: 

- What if Niantic added the **Z** (altitude) together with **X** (latitude) and **Y** (longitude) to actually place you on the map?

Now, i am curious, i tried different methods, to make it work, but regardless of the imputs **XYZ** it does not work. Could it be that the bot does not check for the altitude when it is searching for pokestop?
Gps spoofing programs, both on phones and pc seem to show and use altitude!

I apologize for my bad English, i am not a native speaker.
I apologize for the nonse if it makes no logic or it is not helpful, but i am a vet not a programmer :))

**Comment by somani6** [comment] 2016-08-03 21:34
#2645

**Comment by xiachaolun** [comment] 2016-08-03 21:36
Although it is most likely the API is blocked, your hypothesis of Altitude might be helpful.

**Comment by DrisBigB** [comment] 2016-08-03 21:36
Great idea, +1

**Comment by JjesterWylde** [comment] 2016-08-03 21:37
can we find altitude on the coordinates websites

**Comment by BoBeR182** [comment] 2016-08-03 21:37
Hey, I think it may be related to the hash sent on the DownloadSettings packet (hash="05daf51635c82611d1aac95c0b051d3ec088a930"), this can be relevant since it happened right after the force-update. Could somebody mitmproxy and catch the new hash to publish it here? Thx

I have caught the RPC requests, but I have no idea what to do next. Here is the raw request of /plfe/rpc : http://cdn.auroraen.com/2U2k0f412L24/1254_Request.txt

**Comment by Quado** [comment] 2016-08-03 21:39
i like this idea.

**Comment by JesusNoodl** [comment] 2016-08-03 21:40
Good step in the write direction. +1

**Comment by nfettinger** [comment] 2016-08-03 21:41
The altitude is currently not used by the Niantic API. This issue is probably related to #2645

**Comment by minitaipan** [comment] 2016-08-03 21:41
You could test it at any spot by the ocean/sea, it should be close to the default altitude of the bot (+10m) and probably within the margin of error of the tracker, if any.

**Comment by poutros** [comment] 2016-08-03 21:43
I tried it at Sydney. No luck.

**Comment by nfettinger** [comment] 2016-08-03 21:43
Please update the title to improvement, modify altitude for future use, or this will be closed as a duplicate.

**Comment by somani6** [comment] 2016-08-03 21:43
i was discussing this exact theory the other day as "my" possible soulution against some botting.

**Comment by minitaipan** [comment] 2016-08-03 21:44
Yeap, just tested it at San Francisco Pier 39 and Santa Monica Pier: no success

**Comment by Linewalker** [comment] 2016-08-03 21:45
This is the responce of GetMapObjects().

`System.Collections.ICollection.SyncRoot = {[ { "s2CellId": "5163471669292957696", "currentTimestampMs": "1470260072404" }, { "s2CellId": "5163471671440441344", "currentTimestampMs": "1470260072404" }, { "s2CellId": "5163471673587924992", "currentTimestampMs": "1470260072404" }, { "s2CellId": "51634...`

I Think the problem is not an updated POGOProtos DLL, because currentTimestampMs is in it, CooldownCompleteTimestampMs is POGOProtos asking for.

**Comment by somani6** [comment] 2016-08-03 21:45
@minitaipan thats because the altitude value in the config is not used by the bot as i see it

**Comment by nfettinger** [comment] 2016-08-03 21:48
@somani6 it is unused because the API set by Niantic does not accept an altitude parameter.

**Comment by somani6** [comment] 2016-08-03 21:50
@nfettinger ok :) one way or another the conspiracy theory still stays

**Comment by minitaipan** [comment] 2016-08-03 21:51
well, took 30 sec to test, I have no regrets ;-)

**Comment by omardlr** [comment] 2016-08-03 21:51
ii am debugging the app and when i tried to call the "GetSessionCookie" function, i receive a "Forbiden 403 Error", maybe is a header or niantic is blocking ours IP

**Comment by Jordano3710** [comment] 2016-08-03 21:53
When will this be fixed really wanna use it? all my bot is saying is no usable pokestop's in your area :(

**Comment by poutros** [comment] 2016-08-03 21:54
@Jordano3710 JUST FUCKING WAIT OR PLAY THE GAME NORMALLY!!!!! Seriously, absolutelly noone can give you an eta on this. Wait.

**Comment by desolator7** [comment] 2016-08-03 21:55
Checking for the altitude cannot work for Niantic to identify bots. 
If you are in a high-rise building, altitude can easily be +250 meters

**Comment by Jordano3710** [comment] 2016-08-03 21:55
Mate dont swear at me, it was just a question not a threat....

**Comment by poutros** [comment] 2016-08-03 21:56
Everyone is having the same problem. Repeating it over and over again simply doesn't help.

**Comment by Jordano3710** [comment] 2016-08-03 21:56
Well it was just a question thats all man,

**Closed** 2016-08-07 12:20 UTC
