### ISSUE TITLE
Cannot connect to telegram anymore at 0.8.6

### ISSUE THREAD

**Issue by Festum** [NECROBOTIO/NecroBot#5408] opened 2016-08-12 07:48 UTC
[15:26:53] (ERROR) Unkown Telegram Error occured.

Do I need to fill field TelegramPassword? How? Please update to Wiki.

**Comment by Kampring** [comment] 2016-08-12 08:02
me too ,
 what telegram password ???

**Comment by iHatePython** [comment] 2016-08-12 08:48
If you don't know what it is why are you trying to use it? The bot works fine without it

**Comment by sing1222** [comment] 2016-08-12 08:50
@iHatePython Would you mind teach us?
I also have same problem.

**Comment by theloser** [comment] 2016-08-12 11:42
Telegram is not working with 0.8.6, it's broken. Go back to 0.8.5. or wait until it's fixed. I suggest turning Telegram API of for now.

Also Duplicate of #5323

**Closed** 2016-08-12 11:47 UTC
