### ISSUE TITLE
Problem I found

### ISSUE THREAD

**Issue by lolcheat321** [NECROBOTIO/NecroBot#1977] opened 2016-08-02 04:35 UTC
What is happening?
 (ATTENTION) Encounter problem: EncounterPokemonFled
 (ATTENTION) Encounter problem: EncounterNotFound
(ATTENTION) Encounter problem: EncounterPokemonFled
 (ATTENTION) Encounter problem: EncounterNotFound

**Comment by Squirrel3098** [comment] 2016-08-02 05:11
I'm not a developer but i believe it has to do with slow user to server interaction with niantic servers as it has only happened to me while the loads are high. alternative is that maybe it has to do with sniping?

**Comment by recon88** [comment] 2016-08-02 10:07
Duplicate of #1856

**Closed by recon88** 2016-08-02 10:07 UTC
Labels: duplicate
