### ISSUE TITLE
NO usable pokestops in my area   anyone know how to fix this look s like some sort of bann

### ISSUE THREAD

**Issue by will127** [NECROBOTIO/NecroBot#5309] opened 2016-08-12 03:52 UTC
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by immortalrock** [comment] 2016-08-12 04:02
I am having the same problem. i have tried redownloading it and checking everything but it is in perfect condition so I dontk now what the problem is.

**Comment by SmilingSword** [comment] 2016-08-12 04:08
server down

**Comment by will127** [comment] 2016-08-12 04:09
No  set up a con got it working finally Sent from XFINITY Connect Mobile App------ Original Message ------From: SmilingSwordTo: NECROBOTIO/NecroBotCc: Me, AuthorSent: August 11, 2016 at 11:08 PMSubject: Re: [NECROBOTIO/NecroBot] NO usable pokestops in my area anyone know how to fix this look s like some sort of bann (#5309)server down

**Comment by SmilingSword** [comment] 2016-08-12 04:10
same here maybe ban?

**Comment by SmilingSword** [comment] 2016-08-12 04:10
one of my account cannot be login but after i use another account can be login

**Comment by immortalrock** [comment] 2016-08-12 04:11
I am getting a maximum distance too small error over and over

**Comment by Meeplez** [comment] 2016-08-12 04:12
This is probably because of the net upgrade, even if the application builds the memory may be lost somewhere and not initialized or stored.

**Comment by immortalrock** [comment] 2016-08-12 04:13
lets hope its fixed by tomorrow morning

**Comment by immortalrock** [comment] 2016-08-12 04:13
i think a new update will fix this because this problem has happened before

**Comment by SmilingSword** [comment] 2016-08-12 04:16
my account cannot login from phone

**Comment by TheLamp** [comment] 2016-08-12 04:42
I can pretty much confirm my account has been banned from using Gyms and Pokestops. Using a different account, I was able to visit Pokestops using NecroBot. When on my phone, I wasn't able to visit any Pokestops nor Gyms, when spinning I was instantly given a "try again later".

**Comment by recon88** [comment] 2016-08-12 11:35
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Closed by recon88** 2016-08-12 11:35 UTC
