### ISSUE TITLE
(ATTENTION) Encounter Problem: EncounterNotFound

### ISSUE THREAD

**Issue by SwoleSnorlax** [NECROBOTIO/NecroBot#1960] opened 2016-08-02 02:19 UTC
This message keeps popping up and it is ruining my exp farming, dropped about 50%. Only sometimes does this message not pop up. Sniping still works, but this keeps popping up. I have attached an image of it below. Help would be greatly appreciated :)
![capture](https://cloud.githubusercontent.com/assets/20780890/17314942/c44aeca2-581c-11e6-81ea-bcb83036dbc3.PNG)

**Comment by kamui78** [comment] 2016-08-02 03:02
I have the same issue :\

**Comment by vincentchengws** [comment] 2016-08-02 03:27
Me too!! Same error. Causing my program stuck for one time. Anyone know how to solve it?

**Comment by LiqwdE** [comment] 2016-08-02 03:29
No idea, but I've got it as well. Suprisingly it only occurs on 1 of my 4 necrobot bots that are running. I'm running 2 in hometown, 1 in cali, and the 1 in tokyo is throwing error

**Comment by LiqwdE** [comment] 2016-08-02 03:30
Besides the location, all configs are identical. Maybe location based bug due to translation error?

**Comment by SwoleSnorlax** [comment] 2016-08-02 03:46
just tested your theory out, it's true, all my bots were in tokyo and I switched locations and it was fixed, however exp isnt as good as tokyo

**Comment by SwoleSnorlax** [comment] 2016-08-02 03:55
just kidding it still happens sometimes in other places, but not as much.

**Comment by lolcheat321** [comment] 2016-08-02 04:42
I had this happen in Australia.

**Comment by phingorani** [comment] 2016-08-02 04:58
So I actually tried using the app on my phone where I was getting these errors. The Pokemon appears but disappears as soon as I click on it. Can someone else facing this error confirm this?

**Comment by secw** [comment] 2016-08-02 05:41
I got the error by changing the "MinDelayBetweenSnipes"
with 5000 value the bot wouldn't snipe at all instead of showing encounter problem everytime.
Increasing the value to 60000 the snipe works with minimum encounter problem.

**Comment by recon88** [comment] 2016-08-02 10:07
Duplicate of #1856

**Closed by recon88** 2016-08-02 10:07 UTC
