### ISSUE TITLE
NO useable pokestop found in your area. how can i fix this?

### ISSUE THREAD

**Issue by AddiIgneel** [NECROBOTIO/NecroBot#2689] opened 2016-08-03 21:27 UTC

**Comment by WesleyHilhorst** [comment] 2016-08-03 21:28
Really?

**Comment by DrisBigB** [comment] 2016-08-03 21:28
https://github.com/NECROBOTIO/NecroBot/issues/2645

**Comment by JesusNoodl** [comment] 2016-08-03 21:28
duplicate of #2645

**Comment by Cuuup** [comment] 2016-08-03 21:29
Duplicate of #2654

**Comment by wygasmateusz** [comment] 2016-08-03 21:29
Please read ...
#2645

**Comment by dartmagus** [comment] 2016-08-03 21:37
You are banned

**Comment by nfettinger** [comment] 2016-08-03 21:41
Duplicate of #2645

**Closed by nfettinger** 2016-08-03 21:41 UTC
