### ISSUE TITLE
Niantic - Limit on connections/IP !

### ISSUE THREAD

**Issue by yoshi2323** [NECROBOTIO/NecroBot#2666] opened 2016-08-03 20:39 UTC
Since ~18 hours ago, all my (200+) bots go into "No useable PokeStop found" or softban loop mode within 90 seconds after start.

If i wait 10 mins and try with only 1 or 2 bots its working fine.
Seems like niantic but a limit on connections/ip now...

**Comment by ifbatmanwasreal** [comment] 2016-08-03 20:43
How the fuck do you run 200+ bots?

**Comment by nfettinger** [comment] 2016-08-03 20:44
Duplicate of #2645

**Comment by Sylencer90** [comment] 2016-08-03 20:44
Im fine with 1 bot working at once, why would i need 200 accounts?

**Comment by ifbatmanwasreal** [comment] 2016-08-03 20:44
Clearly he's selling accounts.. But how do you even manage that many?

**Closed by nfettinger** 2016-08-03 20:44 UTC

**Comment by atondo** [comment] 2016-08-03 20:45
Create a bat file and it will lunch as many bot as you want

@echo off
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\SnipeBot\"
start PogoLocationFeeder.GUI.exe
WAIT 5
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\a1\"
start NecroBot.exe
WAIT 5
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\a2\"
start NecroBot.exe
WAIT 5
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\a3\"
start NecroBot.exe
WAIT 5
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\a4\"
start NecroBot.exe
WAIT 5
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\a5\"
start NecroBot.exe
WAIT 5
cd "C:\Users\Chuy\Desktop\botspokemon\8787 SniperBot 0.4.0\a5\"
start NecroBot.exe

**Comment by Rick058** [comment] 2016-08-03 20:45
200 accs ._. damn, I run 3 at max. Currently PokeStop looping though.
Managing isn't difficult, friend of mine coded a fully automatic system and made $2k+ with it already.
