### ISSUE TITLE
transferring is bugged 

### ISSUE THREAD

**Issue by derek0309** [NECROBOTIO/NecroBot#2221] opened 2016-08-02 20:17 UTC
I talked to ppl in discord already and we believe it is bugged, Please check config and dumblog, also pokemons under pokemontoevolve were not transferred before even i set evolve to false, it got transferred after deleting the list so that should also be another bug as well.

[NecroBot-PokeBagStats-2016-08-03-03.xlsx](https://github.com/NECROBOTIO/NecroBot/files/398017/NecroBot-PokeBagStats-2016-08-03-03.xlsx)
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/398018/config.txt)

**Comment by recon88** [comment] 2016-08-02 20:18
Possible duplicate of #2187
There are several known issues with 0.6.1 and transfering

**Closed by recon88** 2016-08-02 20:18 UTC
