### ISSUE TITLE
Using multiply computers

### ISSUE THREAD

**Issue by ewaah** [NECROBOTIO/NecroBot#3795] opened 2016-08-09 11:50 UTC
hi,

i,m using 2 laptops and 1 destkop with ea 1 bot running on them,
does that harm anything?
because i got sofbanend three times on the 0.8.0 version,
and i noticed that the softban happens on the three accounts at the same exact time

Any help would be appreciated

[Nouveau document texte.txt](https://github.com/NECROBOTIO/NecroBot/files/408833/Nouveau.document.texte.txt)

**Comment by GreatApo** [comment] 2016-08-09 11:51
The IP matters not the PC.

**Comment by ewaah** [comment] 2016-08-09 11:54
Ok, so that means is doens't matter?, and second, i now get found no usable pokestops
,there has to be something wrong

**Comment by PassiveModding** [comment] 2016-08-09 11:56
no if your pc's are connected to the same wifi network it will matter

**Comment by ewaah** [comment] 2016-08-09 11:57
they are connected to the same one and 1 is cable

**Comment by ewaah** [comment] 2016-08-09 11:57
and now it works again for a little time its verry weird

**Comment by PassiveModding** [comment] 2016-08-09 12:00
install a vpn on one and run it, with the other leave it without a vpn

**Comment by nekochan23** [comment] 2016-08-09 12:00
I think is a bug? Since the new version, it's very easy to get softban or pokestop doesn't found.
But if you let it a while it will be gone themselves.

**Comment by theloser** [comment] 2016-08-09 12:01
If all systems are on the same network they all use the same (outside) IP address. Only 2 bots per IP work fine, as soon as you run more you'll run into trouble. And no, this is NOT a bug.

**Comment by ewaah** [comment] 2016-08-09 12:03
thanks, ill try the vpn, and @theloser thanks for the clear info!
ill post later how it worked out

**Comment by auth100488** [comment] 2016-08-09 12:22
as said on another thread, cellphones ip are shared... 255.255.255.255 minus the reserved ones ... outputs far from enough for all available devices. (not talking ipv6 here).
Therefore, the said "ip" problem would make no sense.
Also, if you do connect to a free vpn ... you'll eventually share the same ip with another player + you'd have to make sure that the ip comes from the region where you're at ... 
Anyway just my 2 cents!

**Comment by ewaah** [comment] 2016-08-09 12:31
hmm i can understand what you are saying, and i think i get it, it sounded weird in the first place but i dont know for sure, but well see i'm testing alot of different scenarios
like only 1 bot, different configs, other accounts, vpn,
Sadly enough i can't code so

so well see

**Comment by ewaah** [comment] 2016-08-09 13:47
Ok so i used it for an hr now, 1 bot on a laptop and 1 on my desktop, 1 cable and 1 wifi,
both working fine so far, no bans and no pokestop error

So great atm

Thanks for the info and have a great day

**Comment by theloser** [comment] 2016-08-09 14:03
It doesn't make any difference if you are using cable or wifi -- if both systems are connected to the same router they most probably will have the same IP address.

**Comment by ewaah** [comment] 2016-08-09 14:16
yes i figured that out :D, just wanne know if wifi is causing something, i always say you never know
, but thanks for the info, and somethimes it just stops the bot and dont do anything anymore, because of that i thought maybe theres some delay here or at my provider, like playing paragon online and you got dropped out of the server, that problem maybe

**Comment by ewaah** [comment] 2016-08-09 14:16
sorry for bad english.

**Comment by theloser** [comment] 2016-08-09 14:20
Since this is not a bot issue please close this issue, thanks!

**Comment by auth100488** [comment] 2016-08-09 14:22
Well a wifi connection could possibly cause lagspikes and or send the same
packets multiple times... if those are not doible checked before being sent
to the servers .. i guess it could possibly cause some errors .. thats all
in theroy of course

**Comment by ewaah** [comment] 2016-08-09 14:23
Sure, sorry, and @auth100488 thats wahat i thought asswell because i had this problem with a bot from a different game but okay im closing this cya and thanks for the help

**Closed** 2016-08-09 14:23 UTC
