### ISSUE TITLE
Pokemon not being transfered properly bug

### ISSUE THREAD

**Issue by Majamulli** [NECROBOTIO/NecroBot#2438] opened 2016-08-03 09:10 UTC
Hey guys, I am amazed that this hasnt been made an issue yet since I have seen many people on Discord ask about this who have the same problem. We've talked about it and some Moderators said the Devs are informed but with 0.6.3 the problem is still there.

Problem: It's keeping unneccessary pokemon and the pokemon inventory is now full. Settings are:
"KeepPokemonsThatCanEvolve": false,
"KeepMinCp": 2500,
"KeepMinIvPercentage": 95.0,
"KeepMinOperator": "or",
"PrioritizeIvOverCp": true,
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": false, <-- I had it to true as well, doesn't change anything.

The PokemonTransferFilter has been set to 2500 CP and 95 IV for each of the pokemon listed there, no new pokemon have been added. The PokemonsNotToTransfer is empty except for the 6 unobtainable pokemon.
I have had people send me their config and used those as well. I have talked with other people and checked their config. I have - as far as I can tell - done everything I can and it's still not transfering pokemon.
They are not favorited either.

I dumped the Pokemon stats to see what I actually have and why my inventory is full and for example I have:
Bulbasaur 582 CP - 77 IV
Bulbasaur 193 CP - 65 IV

It should have transfered the second one but it's not doing it. This first happened with the 0.6.0 release. 0.6.2 didn't work either and 0.6.3 is still bugged. I have completly redownloaded the 0.6.2 version to make sure nothing old is interfering and it still didn't help. So here I am making this thread and hope it'll get addressed soon.

**Comment by emwedk** [comment] 2016-08-03 09:17
have you checked if Bulbasaur is in the 
  "PokemonsNotToTransfer": [

  "PokemonsTransferFilter": {

**Comment by actislav** [comment] 2016-08-03 09:18
check first PokemonsNotToTransfer in global, and PokemonsTransferFilter for each pokemon kind and past it here.  Be aware that for now "Moves": [] in PokemonsTransferFilter per pokemon works like keep everything which has any type of attack you write there

**Comment by Majamulli** [comment] 2016-08-03 09:19
I have already answered both of that in the text I wrote. The PokemonNotToTransfer is empty except for the 6 uncatchable ones.
The PokemonTransferFilter has the default Pokemon in it but all stats changed to min 2500 CP and 95 IV. There is NO Bulbsaur in there!
"PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
 "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 3000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 3000,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or"
    }
  },

**Comment by Jonasdero** [comment] 2016-08-03 09:37
i got the same problem no pokemon is transfered anymore like i got 40 pidgeys that are just laying around

**Comment by Majamulli** [comment] 2016-08-03 09:44
Alright I found the "error".
From the beginning until - including - version 0.5.0 the KeepMinDuplicatePokemon = 1 meant that you keep 1 of each pokemon. Apparently this was changed with version 0.6.0 and above. Now this means that it really keeps a Duplicate = making it 2 of each Pokemon if set to 1.
Sadly this information has not been properly transfered to the users and so many people had "problems" with the bot just not transfering anymore. And of course no one wanted to set it to 0 cause with the old settings it would mean that it transfers all of your pokemon.
I will not manually close this issue for now in case other people come here looking for the same problem and I hope that this option can be renamed to make it clear. I know that the meaning of the words describes exactly what it does now, but it didn't before so it should really be changed now to something like "NumerOfEachPokemonToKeep" like suggested in another issue.

If I misunderstood something and am talking total crap here then please let me know :)

**Comment by Majamulli** [comment] 2016-08-03 09:53
Alright another user wrote here: https://github.com/NECROBOTIO/NecroBot/issues/2442 that setting KeepMinDuplicatePokemon to 0 resulted in him not having 1 of 4 different pokemon. So it seems that setting it to 0 still means that it won't keep even 1 of each pokemon. Which means there really is some other bug. At this point I am still unsure of what's happening and I will wait for someone with more knowledge to help me out.

**Comment by actislav** [comment] 2016-08-03 10:05
what version do you use

**Comment by Darkztar** [comment] 2016-08-03 10:06
I had the same problem and after deleting complete the content of the PokemonsTransferFilter even if there are other pokemon mentioned, it seems to work and the bot transfer my pokemon.

**Comment by Majamulli** [comment] 2016-08-03 10:07
@actislav the latest 0.6.3

I just set KeepMinDuplicatePokemon to 0, it transfered a lot of pokemon BUT it didn't keep 1 of each. There are many pokemon which I have 0 now. So that definitly didn't help!

**Comment by actislav** [comment] 2016-08-03 10:08
in last version was bug, global KeepMinOperator not to be overrided by local

**Comment by actislav** [comment] 2016-08-03 10:09
pls past here your full config as it was at the moment of incorrect behavior

**Comment by actislav** [comment] 2016-08-03 10:10
if KeepMinDuplicatePokemon = 0 then all pokemon not to meet min requirements will be transferred

**Comment by Wcidd** [comment] 2016-08-03 10:10
I'm going to label this as a bug so the devs can check one last time

**Comment by Majamulli** [comment] 2016-08-03 10:11
http://pastebin.com/qvrGXcCT
This is the config I used right after having updated to 0.6.0 and this was the first time the pokemon inventory got full.

**Comment by noremac13** [comment] 2016-08-03 10:35
I have a similar problem.  I have tried everything with multiple bots and they all have this same issue, although I think many bots are based off Necro so that makes sense.

I set transfer duplicate to 0, which removed a couple of the bad ones.  Then I deleted everything out of the "PokemonsTransferFilter" section which removed a couple more of the bad ones.

This is what my config looks like now:
`{
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 2500,
  "KeepMinIvPercentage": 95.0,
  "KeepMinOperator": "or",
  "PrioritizeIvOverCp": true,
  "KeepMinDuplicatePokemon": 0,
  "UseLuckyEggsMinPokemonAmount": 50,
  "UseLuckyEggsWhileEvolving": true,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  ],
  "PokemonsNotToTransfer": [
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "bulbasaur",
    "charmander",
    "squirtle",
    "caterpie",
    "metapod",
    "weedle",
    "kakuna",
    "pidgey",
    "pidgeotto",
    "rattata",
    "spearow",
    "ekans",
    "pikachu",
    "sandshrew",
    "nidoranFemale",
    "nidoranMale",
    "clefairy",
    "vulpix",
    "jigglypuff",
    "zubat",
    "oddish",
    "paras",
    "venonat",
    "diglett",
    "meowth",
    "psyduck",
    "mankey",
    "growlithe",
    "poliwag",
    "abra",
    "machop",
    "bellsprout",
    "tentacool",
    "geodude",
    "ponyta",
    "slowpoke",
    "magnemite",
    "doduo",
    "seel",
    "grimer",
    "shellder",
    "gastly",
    "drowzee",
    "krabby",
    "voltorb",
    "exeggcute",
    "cubone",
    "hitmonlee",
    "koffing",
    "rhyhorn",
    "horsea",
    "goldeen",
    "staryu",
    "eevee",
    "omanyte",
    "kabuto"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {},`

Even after all that I opened the account in PokeIV and saw a huge list of stuff listed as transfer candidates that weren't being transferred.  I have the same settings 2500CP and 95IV in both programs so the lists should be identical if everything worked correctly.  I counted 74 Pokemon that should have been transferred that weren't.

This is what the same list looks like in PokeIV with the same settings [http://puu.sh/qoigA/76fdd9d0fd.png](url)

**Comment by Naprosnia** [comment] 2016-08-03 10:36
Yep. I got this problem. It should be reverted to any version that work like 0.5.0.

**Comment by noremac13** [comment] 2016-08-03 10:43
Also I should add I am currently using 0.5.0 and this problem has existed in every previous version of Necro or any Necro based fork bot I have used.  I have yet to find anything that transfers properly.

**Comment by Wcidd** [comment] 2016-08-03 11:31
Pull request has been sent to fix this bug

**Closed by Wcidd** 2016-08-03 11:31 UTC
Labels: bug, ready

**Comment by Naprosnia** [comment] 2016-08-03 11:56
This pull request fix this error finally ;)
fix transfer bug ( usage of global KeepMinOperator instead of local) #2446

**Comment by Jonasdero** [comment] 2016-08-03 13:49
i tried some changes in my config the problem is the following:

if u set "KeepPokemonsThatCanEvolve": true,
then all pokemon will not be transfered if they are in your PokemonToEvolveList

else all are transfered that doesnt meet ur minimum conditions

**Comment by noremac13** [comment] 2016-08-03 19:29
When will this fix be pushed live?  I have auto-update on and have not received any updates and the bug is still present.

**Comment by DeadlyHollowz** [comment] 2016-08-08 15:27
I have found a fix for this problem.
Simly delete   "KeepMinLvl": 6, and "UseKeepMinLvl": true, from the config file. this will instantly fix the problem. Enjoy :)

**Comment by ochirutenshi** [comment] 2016-08-10 14:39
deadly, which "KeepMinLvl": 6, and "UseKeepMinLvl": true? global or local?
