### ISSUE TITLE
Crash after some time

### ISSUE THREAD

**Issue by djdookie** [NECROBOTIO/NecroBot#1630] opened 2016-08-01 01:13 UTC
After some time running the bot v0.5.0 (~1 hour, for two times now) it crashes with the following exception:

`PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException was unhandled
Message: An unhandled exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' occurred in mscorlib.dll`

Can someone pls fix that? And ideally the exception should be catched and not crash the bot. ;)
Never had those problems before, but today I tried to run multiple bots simultaneously for the first time (but with different auth config).

**Comment by sflszyt** [comment] 2016-08-01 01:49
Yah. desperately need a 'autoreconnect' feature.

**Comment by nongdun** [comment] 2016-08-01 02:09
I'm already pull request on #1641

**Comment by djdookie** [comment] 2016-08-01 12:08
I got additional different crashes with v0.5.0 after some time:
`System.ArgumentNullException was unhandled
Message: An unhandled exception of type 'System.ArgumentNullException' occurred in mscorlib.dll
Additional information: This value can't be NULL.`
I think it was the Rocket API again after throttling API calls becuase niantic servers got slow.

I am sorry, I unfortunately was only able to check the exception with Visual Studio debugger after crashing, now I can't trace down the line or function that crashed, because it ran in a cmd window.
Same again, bot stops working and crashes, which pretty sucks. :-/

**Comment by nongdun** [comment] 2016-08-01 12:12
No matter what the cause, I just let the account login again, and it works. :P

**Comment by djdookie** [comment] 2016-08-01 12:15
Does it prevent the client crashes? Someone should catch the exceptions...

**Comment by nongdun** [comment] 2016-08-01 12:42
State machine already catch the exceptions, I detected the frequency of crashes, if too frequently then re-login.

**Comment by djdookie** [comment] 2016-08-01 13:05
Man you guys rock! ;)
Fix for exception handling regarding this errors is already pulled in #1742.
Cheers!

**Comment by recon88** [comment] 2016-08-01 18:38
Has been Merged into the project

**Closed by recon88** 2016-08-01 18:38 UTC
