### ISSUE TITLE
Pokemon Go updated. Bot not working anymore for now (no pokestop or red error)

### ISSUE THREAD

**Issue by lizhao12345** [NECROBOTIO/NecroBot#2658] opened 2016-08-03 20:27 UTC
Pokemon Go just had a new patch 20 mins ago, Bot not working anymore (red error or no pokestop available). please update the bot, thanks.

**Comment by wowstin** [comment] 2016-08-03 20:29
They are working on it, issue is aware of.

**Comment by abratar** [comment] 2016-08-03 20:30
after reading your comment i thought pokemon go the "APP" has updated... but its not-.- i guess you mean their api or something

**Comment by elmaarmut** [comment] 2016-08-03 20:33
I think there is a permanent IP soft-ban in place. I logged in from my phone with my home Wifi and used an incense, pokemon ran after 1st pokeball. I reconnected with my 4.5G, and I was able to catch the 2nd pokemon from the incense.

I'd say leave the bot alone for now and let the pros handle it. I think they are trying to block external devices that send high number of inquiries to the server.

**Comment by nfettinger** [comment] 2016-08-03 20:33
Duplicate of #2645

**Comment by carlanivans** [comment] 2016-08-03 20:33
https://otakukart.com/animeblog/2016/08/03/minimum-scanning-time-doubled-see-effects/

**Comment by carlanivans** [comment] 2016-08-03 20:33
read this

**Comment by Venzhel** [comment] 2016-08-03 20:34
Everybody aware of this. Just stop pushing the dev, let they do their job and at least we can stop asking them and start praying they will find the way to fix this.

**Closed** 2016-08-03 20:33 UTC
