### ISSUE TITLE
[Suggestion] Add proxy functionality and a hour based schedule

### ISSUE THREAD

**Issue by bonny1992** [NECROBOTIO/NecroBot#2110] opened 2016-08-02 16:44 UTC
I was using this awesome bot on a EC2 server and now it says that my ip is blocked from Niantic servers; so it would be awesome if we can add a proxylist and cycle through that.

Also, it's a bit suspicious if a "trainer" walks around the same location for 24 hours nonstop, so a hour/day based schedule would be useful, since I could set my bot to wander from 2PM to 8PM every day except for Sunday or something like this.

**Comment by recon88** [comment] 2016-08-02 16:48
Duplicate of #1945

**Closed by recon88** 2016-08-02 16:48 UTC

**Comment by bonny1992** [comment] 2016-08-02 16:51
@recon88  also for the schedule?

**Comment by recon88** [comment] 2016-08-02 16:52
You can setup a Windows Task or Cronjob on Linux to achieve that.

**Comment by bonny1992** [comment] 2016-08-02 16:56
Wouldn't be killing the process being sometimes "risky"? I mean, sometimes can it lose some data and records, or is it safe?

**Comment by recon88** [comment] 2016-08-02 16:56
Should be safe

**Comment by bonny1992** [comment] 2016-08-02 17:06
Oh ok, then, if it's safe I understand.
