### ISSUE TITLE
[Suggestion] Egg Incubator Improvement

### ISSUE THREAD

**Issue by Tomabl** [NECROBOTIO/NecroBot#2008] opened 2016-08-02 08:01 UTC
The egg incubator always develops the first egg "in row", how about implementing the user choice to only develop 10km eggs (if available)? Thanks!

**Comment by Oolaruu** [comment] 2016-08-02 08:23
https://github.com/NECROBOTIO/NecroBot/issues/1579

**Comment by Whosdaman** [comment] 2016-08-02 10:09
How about longest eggs first flag?

**Comment by recon88** [comment] 2016-08-02 10:20
Duplicate of #1579

**Closed by recon88** 2016-08-02 10:20 UTC
