### ISSUE TITLE
when spoofing willl be banned

### ISSUE THREAD

**Issue by panoszik** [NECROBOTIO/NecroBot#3417] opened 2016-08-08 22:57 UTC
i heard from sources that in the next or the following update fake gps will ne terminated..is it true?

**Comment by GummiBoat** [comment] 2016-08-08 22:58
It already is a soft-ban. I guess they have no problem, turning it into a real ban, if you move too far. It won't be a problem to work around though probably, I don't think it will disable Sniping either.

**Comment by MrYohann** [comment] 2016-08-08 23:05
Good evening / good morning : I just got banned at the time , my account is no longer accessible .. But I used the bot in my city within 5km from home. (Sorry for my bad english I 'm french)

**Comment by carlos0202** [comment] 2016-08-08 23:09
did you get banned today?

**Comment by burntable** [comment] 2016-08-08 23:11
probably not. auth servers having issues today.

**Comment by MrYohann** [comment] 2016-08-08 23:11
There are 10 minutes is the First time except once a softban

**Comment by burntable** [comment] 2016-08-08 23:15
You mean you can't login since 10 minutes? Have you tried another acc already?

**Comment by MrYohann** [comment] 2016-08-08 23:18
Yes, I tried with two other accounts and they work

**Comment by CDAGaming** [comment] 2016-08-08 23:20
Daw Shiz, that's why my trainer club acc got banned :(

Oh, Well :P

**Comment by MrYohann** [comment] 2016-08-08 23:24
With the application and the bot that does not work but with another bot works ca ... weird http://prntscr.com/c3ar1d

**Comment by nfettinger** [comment] 2016-08-09 13:50
This is likely a configuration issue, and not a bug in the code. Closing

**Closed by nfettinger** 2016-08-09 13:50 UTC
