### ISSUE TITLE
[Suggestion] Pokemons and items we have at the moment

### ISSUE THREAD

**Issue by henriquemaciel** [NECROBOTIO/NecroBot#2118] opened 2016-08-02 17:06 UTC
I would like to make a suggestion in the title bar could have information on how many Pokemons and items we have at the moment.

![image](https://cloud.githubusercontent.com/assets/20246124/17337699/45f6d82c-58ba-11e6-93b7-c9e543d6e169.png)

**Comment by recon88** [comment] 2016-08-02 17:20
Duplicate of #1863

**Closed by recon88** 2016-08-02 17:20 UTC
