### ISSUE TITLE
Proxy support not working?

### ISSUE THREAD

**Issue by athanatos1** [NECROBOTIO/NecroBot#3415] opened 2016-08-08 22:45 UTC
We need something that confirms in the bot that the proxy is loaded and working, which also shows current ip address in use. 

Getting soft banned with more then 3 accounts and also, what KIND of proxy does the bot support?? Socks 5, regular proxies, etc?

**Comment by djdookie** [comment] 2016-08-08 23:21
Duplicate of my earlier issue #3235

**Comment by nfettinger** [comment] 2016-08-09 13:51
Duplicate

**Closed by nfettinger** 2016-08-09 13:51 UTC
