### ISSUE TITLE
Bot transferring everything

### ISSUE THREAD

**Issue by Walkingdead5443** [NECROBOTIO/NecroBot#3942] opened 2016-08-09 16:28 UTC
When I open the bot it starts to auto transfer all my pokemon away, regardless of if I have minduplicatepokemon and 1 or more. please fix!!

**Comment by nfettinger** [comment] 2016-08-09 16:29
Please use the Discord chat rooms for configuration help.
Could be duplicate of #3338

**Closed by nfettinger** 2016-08-09 16:29 UTC
