### ISSUE TITLE
system null reference

### ISSUE THREAD

**Issue by dizzyddevil** [NECROBOTIO/NecroBot#3510] opened 2016-08-09 02:42 UTC
[22:40:51] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24

**Comment by 20giis** [comment] 2016-08-09 02:42
me too!!

**Comment by Magnaleikha91** [comment] 2016-08-09 02:43
Like mine right now :o

**Comment by Seyrenvox** [comment] 2016-08-09 02:43
mine too XD

**Comment by vvvsrx** [comment] 2016-08-09 02:43
me too~

**Comment by LTGRaven** [comment] 2016-08-09 02:43
same

**Comment by Enragedmaster** [comment] 2016-08-09 02:43
Same

**Comment by ridoknight** [comment] 2016-08-09 02:44
same

**Comment by Magnaleikha91** [comment] 2016-08-09 02:45
Since it's doesn't work and I have the previous version running well, I use the previous one for now.

**Comment by 20giis** [comment] 2016-08-09 02:46
while everybody is here, does anyone have a 100k+ config? :santa:

**Comment by Reborn1990** [comment] 2016-08-09 02:46
mine too. this is my data dump just posting for tracking.

[19:45:43] (ERROR) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__11.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by ryfoster** [comment] 2016-08-09 02:47
same

**Comment by TheGreaper** [comment] 2016-08-09 02:50
7.8 killed the programming wtf

**Comment by GitClucked** [comment] 2016-08-09 02:52
I went back down to 7.2 and its working fine so far.

**Comment by canuckle604** [comment] 2016-08-09 02:53
how do you go back to 7.2

**Comment by GitClucked** [comment] 2016-08-09 02:55
Download it. :P. Just go back to the release page and download it.

**Comment by fartb0i** [comment] 2016-08-09 02:56
It's running just fine on one of my logins... but other two (one google and one ptc) have the same issue.

**Comment by diogocmartins** [comment] 2016-08-09 02:57
7.8 started runing fine again..

**Comment by P-rus** [comment] 2016-08-09 02:59
I have a similar problem.  It seems intermittent.  I ran for 5 hours last night, then it stopped.  Again this morning for 3 hours.  Now it refuses to run at all.  Here's the text:

[error.docx](https://github.com/NECROBOTIO/NecroBot/files/408118/error.docx)

**Comment by 20giis** [comment] 2016-08-09 03:01
it works now <3 <3

**Comment by Mohammed9531** [comment] 2016-08-09 03:06
It's working fine now.

**Comment by nfettinger** [comment] 2016-08-09 14:06
Duplicate of #3295

**Closed by nfettinger** 2016-08-09 14:06 UTC
Labels: duplicate
