### ISSUE TITLE
Update and Info line spammed

### ISSUE THREAD

**Issue by BigAlGit** [NECROBOTIO/NecroBot#2200] opened 2016-08-02 19:37 UTC
I am getting these lines a lot:

[15:34:00] (UPDATE) [Evolves] Potential Evolves: 0
[15:34:00] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:34:04] (UPDATE) [Evolves] Potential Evolves: 0
[15:34:04] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:34:10] (UPDATE) [Evolves] Potential Evolves: 0
[15:34:10] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:34:17] (UPDATE) [Evolves] Potential Evolves: 0
[15:34:17] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:34:26] (UPDATE) [Evolves] Potential Evolves: 0
[15:34:27] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:34:34] (UPDATE) [Evolves] Potential Evolves: 0
[15:34:35] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151

If I have it set to show pokeball count, it adds it in above the UPDATE line as well.  It keeps doing this every few seconds and I can't seem to find any way to make it do it way less.  When there is one to evolve it shows:

[15:36:37] (UPDATE) [Evolves] Potential Evolves: 1
[15:36:37] (INFO) Waiting to evolve 1 Pokemon once 191 more are caught! (169/360 for 90% inventory)
[15:36:37] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:36:39] (INFO) Pokemon Drowzee (14278280063932003894) renamed from Drowzee to Drowzee32.
[15:36:43] (UPDATE) [Evolves] Potential Evolves: 1
[15:36:43] (INFO) Waiting to evolve 1 Pokemon once 191 more are caught! (169/360 for 90% inventory)
[15:36:43] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:36:45] (INFO) Pokemon Drowzee (14278280063932003894) renamed from Drowzee to Drowzee32.
[15:36:54] (UPDATE) [Evolves] Potential Evolves: 1
[15:36:54] (INFO) Waiting to evolve 1 Pokemon once 191 more are caught! (169/360 for 90% inventory)
[15:36:55] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:36:59] (UPDATE) [Evolves] Potential Evolves: 1
[15:36:59] (INFO) Waiting to evolve 1 Pokemon once 191 more are caught! (169/360 for 90% inventory)
[15:36:59] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151
[15:37:11] (UPDATE) [Evolves] Potential Evolves: 1
[15:37:11] (INFO) Waiting to evolve 1 Pokemon once 191 more are caught! (169/360 for 90% inventory)
[15:37:11] (INFO) Amount of Pokemon Seen: 128/151, Amount of Pokemon Caught: 127/151

**Comment by recon88** [comment] 2016-08-02 19:38
Duplicate of #2182

**Closed by recon88** 2016-08-02 19:38 UTC
