### ISSUE TITLE
V 0.5.0 - waste razz berry

### ISSUE THREAD

**Issue by OgaaaH** [NECROBOTIO/NecroBot#1914] opened 2016-08-01 21:59 UTC
[04:56:04] (PKMN) (CatchSuccess) | (Normal) Scyther Lvl: 20 CP: (1101/1185) IV: 56.00% | Chance: 20.09% | 55.21m dist | with a PokeBall (193 left). | Candies: 69
[04:56:09] (BERRY) Used Razz Berry | 0 remaining
[04:56:12] (PKMN) (CatchSuccess) | (Normal) Magnemite Lvl: 22 CP: (522/559) IV: 74.00% | Chance: 31.92% | 55.51m dist | with a PokeBall (192 left). | Candies: 6

**Comment by hilycker** [comment] 2016-08-01 22:28
Try to be more 	thorough please,
What I can see is you catched a scyther, used last razz berry you had, then catched a magnmite. Where's the problem?

**Comment by recon88** [comment] 2016-08-01 22:32
Duplicate of #1647

**Closed by recon88** 2016-08-01 22:32 UTC

**Comment by OgaaaH** [comment] 2016-08-01 22:52
it catch sycther without razz berry , the last razzbery is used to catch magnemite with lower cp than scyther

**Comment by hilycker** [comment] 2016-08-01 23:03
Check settings expecially catch chance because scryther's is lower than magnemite's so it seems it's behaving normally
