### ISSUE TITLE
NullRefernce Exception

### ISSUE THREAD

**Issue by Sprinting** [NECROBOTIO/NecroBot#2542] opened 2016-08-03 15:37 UTC
This has been happening quite often in the past day, I've changed nothing in `config.json` except starting coordinates and sniping locations 
![image](https://cloud.githubusercontent.com/assets/16353379/17371643/4a23b834-59be-11e6-97a4-c1e56ca096e0.png)

**Comment by nfettinger** [comment] 2016-08-03 15:44
Duplicate of #2521

**Closed by nfettinger** 2016-08-03 15:44 UTC
