### ISSUE TITLE
CatchFlee but Pokestops Works

### ISSUE THREAD

**Issue by Styla13374** [NECROBOTIO/NecroBot#5289] opened 2016-08-12 01:04 UTC
i have this issue anyone have this too?

Pokestops Works good but all Pokemos Flee

**Comment by furkan75** [comment] 2016-08-12 01:09
me too

**Comment by kurozani** [comment] 2016-08-12 01:12
you level up, pokemon harder to caught

config your setting?

use raxxberry in config use "and" change it to orr

because in default it means only pokemon with 90IV, 0,5 chance and 1000 CP will get razzberry

**Comment by Styla13374** [comment] 2016-08-12 01:17
i have this problemm since 40 minutes and the last hours the bot is worked good i don't edited config :S

**Comment by furkan75** [comment] 2016-08-12 01:36
now it says not foundable pokestops in your area, is your max distance too small???

**Comment by YahyahyahCF** [comment] 2016-08-12 02:01
You are softbanned, just need to close the bot for a while, then everything will be normal again

**Comment by furkan75** [comment] 2016-08-12 02:05
i am not softbanned, it is been half an hour and it still doesnt work

**Comment by YahyahyahCF** [comment] 2016-08-12 02:07
I got the exact same issue, what worked for me was to stay away for like 2 hours, then it worked normally again.

**Comment by miracho** [comment] 2016-08-12 02:22
same.

**Comment by jonsnowwatch** [comment] 2016-08-12 02:24
100% catch-flee but can use pokestops, is this a new kind of soft ban?

**Comment by Gernatch** [comment] 2016-08-12 02:29
Same here.

**Comment by TagorHP** [comment] 2016-08-12 02:36
are you guys also open pogo in your gadgets?
please close it while running the bot.

**Comment by Gernatch** [comment] 2016-08-12 02:39
Not sure what you mean by that. I don't think so.

**Comment by V-E-O** [comment] 2016-08-12 03:53
Snipe->CatchFlee->SoftBan->ALWAYS FLEE(PERMANENT BAN?)

**Comment by xshadowoflightx** [comment] 2016-08-12 03:57
same here, pokestop works but catching doesn't

**Comment by ohkered** [comment] 2016-08-12 06:08
all i get is pokemon flee between pokestop and snipe. What is going on?

**Comment by ThomasSRL** [comment] 2016-08-12 06:40
Same here on version 8.5
Was using 33 speed and around 5000-2000 delays...

**Comment by ThomasSRL** [comment] 2016-08-12 06:47
Has anyone gotting this kind of (soft?)ban removed yet? :)

**Comment by fakeskill** [comment] 2016-08-12 07:04
same thing guys who can help us ? 

am not soft banned but i can't catch pokemons

**Comment by jackdaripperman** [comment] 2016-08-12 07:11
Same problem here, any word on a solution yet?

**Comment by Cyrus-Wong** [comment] 2016-08-12 07:22
same here

**Comment by robbiedudeskie** [comment] 2016-08-12 07:23
Same problem but I can use my other account after the 8.6 update though.. If we are all perma banned, then why are we able to loot at pokestops, battle at gyms though? Lets not speculate things.. Lets wait a word from the devs about this issue.. I stopped botting my main one and manually playing it now just to be sure..

**Comment by andre1974** [comment] 2016-08-12 07:37
Same here

**Comment by robbiedudeskie** [comment] 2016-08-12 08:32
Still no words from the devs and its already an hour and still having this catchflee issue..

**Comment by OH00914** [comment] 2016-08-12 08:37
its the issue of 0.8.6 update, it work fine on 0.8.5

**Comment by xshadowoflightx** [comment] 2016-08-12 08:40
^it has nothing to do with the update, same catch flee issue when i played with my phone

**Comment by spdragon** [comment] 2016-08-12 09:00
after my search, i believe there are 3 new ban are implemented:
1. Catch flee ban (can loot pokestop but every pokemon are flee from us)
2. Pokestop ban (can catch pokemon but can't loot pokestop)
3. ID delete ban (account cannot login and data had been deleted in the server)

I'm using Necrobot with sniping, running 2 google account simultaneously with different ip, one of it place in vmware, 60km/h walking speed and one of it getting Catch flee ban and another one is fine. 
After 3 hours,my banned account is haven't unban. Im stop botting after my account get banned, so i hope anyone could find out what causing the ban and is it unbanable.

**Comment by OH00914** [comment] 2016-08-12 09:07
will my account get unban?

**Comment by rajaomair** [comment] 2016-08-12 09:11
SAMEEEEEEEEEEE

**Comment by rajaomair** [comment] 2016-08-12 09:12
can get pokestops but not pokemons

**Comment by OH00914** [comment] 2016-08-12 09:14
solution pls..

**Comment by deguitz06** [comment] 2016-08-12 09:23
Holy crap I was just curious if this bot would work. I made a new account just to be sure, and oh boy did it work alright and got me to lvl 22 (I stopped there cuz I really didn't want to get banned for this}. Until this type of ban happened. The first time I encountered it, I tried fixing it via spinning the poke stops, and at first poke stops didn't work so I tried fixing it by spinning it 40x or so until I got the items. I thought I was free from the soft ban so I tried catching some pokemon just to be sure. I was surprised that none of the pokemon I encountered even want to be catched. And so, I looked through everywhere searching for unbanning for this type of soft ban but to no luck, I couldn't find any fix. Please help us? I wanna start on playing with this account for realz and stop using the bot once this gets fixed.

**Comment by robbiedudeskie** [comment] 2016-08-12 09:54
Ok people this gets worse by the hour.. Now when i go visit everypokestops, it says "try again" and not even one pokemon on the map.. When I restarted the app, all I get is a blank map..

Any of you guys here experiencing this problem? Its just my 2nd day to use the bot

**Comment by spdragon** [comment] 2016-08-12 10:11
someone have unbanned flee ban after 28 hours
![aaaz](https://cloud.githubusercontent.com/assets/20884593/17619441/086727cc-60b8-11e6-860e-68acca119e34.jpg)

**Comment by OH00914** [comment] 2016-08-12 10:11
any helps?

**Comment by deguitz06** [comment] 2016-08-12 10:39
So basically I just have to stop and wait for the ban to be lifted? My config was set to run for 180 kph and I set teleport to true.  Maybe that was the cause of my ban.  I have only been botting for like 2.5 hours. If mine gets fixed later on, I will resume on playing normally. :D

**Comment by leoryn** [comment] 2016-08-12 11:34
I think those ban types are new. This morning I was able to catch pokemons and couldnt loot any poketstops **UNTIL I took a gym**. After that point everything was normal. Half an hour ago I had another issue this time I can loot pokestops but every pokemon flees. I will now go and try to take another gym.

**Comment by deguitz06** [comment] 2016-08-12 11:35
Even with this ban, I can still take gyms. I think this ban's target is to prevent the pokestop spin unban method.

**Comment by fakeskill** [comment] 2016-08-12 11:39
For me I can't even take any gym when i enter its give me error and left the gym

**Comment by recon88** [comment] 2016-08-12 11:40
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Closed by recon88** 2016-08-12 11:40 UTC

**Comment by OH00914** [comment] 2016-08-12 12:22
so when will i get unban? how long should i wait?

**Comment by fakeskill** [comment] 2016-08-12 12:31
Who knows this thing is new to all of us
