### ISSUE TITLE
Suggestion: Catch Pokémon Only Above IV

### ISSUE THREAD

**Issue by Simpuhl** [NECROBOTIO/NecroBot#3222] opened 2016-08-08 14:38 UTC
Would it be possible to implement a feature to only catch Pokémon that are above a specific IV level we can customize? 

My scenario is that I've completed my Pokédex, I can care less about leveling so much. I'd just like to collect high level IV Pokémon now and get ultra balls and great balls and not waste them on crap that's under 95% IV. 
*I know I can configure the balls part.

No rush, but I think others may be thinking the same way I am. 

Thank for all your hard work by the way.

**Comment by progz** [comment] 2016-08-08 14:52
I am wondering if it's possible to know the IV of a Pokemon before catching it ?

**Comment by Simpuhl** [comment] 2016-08-08 15:08
It was possible before, not sure with the new API.

But I know that the bot can see it when you see the catch failed or catch escape or catch flee, so I think it can

**Comment by meetloaf13** [comment] 2016-08-08 16:24
This is what I want as well.  I haven't completed my Pokedex yet (where are you farming Simpuhl?)

After a certain level, it's pretty obvious to be spotted using a bot if you level too high.

**Comment by Simpuhl** [comment] 2016-08-08 16:26
@meetloaf13 

I farmed mostly in Long Beach, Santa Monica, and then I setup the snipe tool to catch rares.

**Comment by meetloaf13** [comment] 2016-08-08 16:28
hmmm.  Looks like need to learn the snipe tool.  I thought that was for battling arenas.  

Thanks!

FWIW.  I've already changed my config to not evolve pidgeys and the like, I don't really care for the XP.  I'm down to about 27K/hr

**Comment by Simpuhl** [comment] 2016-08-08 16:35
I enabled the sniper features and downloaded the pogo feeder as I couldn't figure out how to configure it to just use pokezz.com 

Take a look at the wiki for the download link of pogo feeder

**Comment by JaEdmuva** [comment] 2016-08-08 17:05
I agree @Simpuhl, Just as an additional idea, I think the catching should be done when the pokemon has a IV above the IV of the same pokemon you actually have in your inventory.

**Comment by PokemasterMike** [comment] 2016-08-08 17:23
If this gets implemented, it would be a good idea also add an option for cp/level/catch chance. Just make it customizeable, everyone should be happy :)

**Comment by Simpuhl** [comment] 2016-08-08 17:24
Yeah thats good idea too, only catch if higher than current one

**Comment by meetloaf13** [comment] 2016-08-08 17:28
The PogoFeeder is pretty dang slick.  

Do you find this behavior a lot?
http://i.imgur.com/n7nhaXa.png

Does that mean it isn't finding anything there and skips to the next one?  Is there a delay I should set so it can snipe more effectively?

**Comment by Simpuhl** [comment] 2016-08-08 17:32
I do get that, I believe there was "nothing there" so it switched back.

Another bug I get is that it starts to catch something and Ill get some catchEscape a few times and then nothing... no catchFlee or catchSuccess it just starts doing something else.

But it works sometimes.

**Comment by meetloaf13** [comment] 2016-08-08 17:33
k, thanks!

**Comment by nfettinger** [comment] 2016-08-11 14:48
Catching lower level Pokemon increases your XP and candy. Working as designed, suggestion wont fix.

**Closed by nfettinger** 2016-08-11 14:48 UTC
Labels: enhancement
