### ISSUE TITLE
Using my Ultra balls on EVERYTHING. My setting's are correct.

### ISSUE THREAD

**Issue by AceTrainer** [NECROBOTIO/NecroBot#1844] opened 2016-08-01 17:55 UTC
"UseGreatBallAboveCp": 750,
  "UseUltraBallAboveCp": 1300,
  "UseMasterBallAboveCp": 2500,
  "UseGreatBallAboveIv": 98,
  "UseUltraBallAboveIv": 99,
  "UseGreatBallBelowCatchProbability": 40.0,
  "UseUltraBallBelowCatchProbability": 25.0,
  "UseMasterBallBelowCatchProbability": 0.0,

But it is still using ultra balls on everything. on a pidgey CP 320 with %40 IV, catch chance 70, and it still used ultra balls. It could be catch cance 100 and it is using ultra balls no matter what. SOMEONE PLEASE HELP

**Comment by recon88** [comment] 2016-08-01 17:56
Duplicate of #1746

**Closed by recon88** 2016-08-01 17:56 UTC

**Comment by somani6** [comment] 2016-08-01 17:58
nope your settings are not correct :)
"UseGreatBallBelowCatchProbability": 0.4 equals to 40%, not 40.0

In your Case the bot is using UltraBalls for everything below 4000% catch rate

**Comment by AceTrainer** [comment] 2016-08-01 17:59
Ahhhh. I disgrace myself. Thank you for your guidance.
