### ISSUE TITLE
GPX pathing resets when API is throttled.

### ISSUE THREAD

**Issue by Gobu70** [NECROBOTIO/NecroBot#5032] opened 2016-08-11 10:31 UTC
When I get the "server unstable, throttling API" message, the GPX path stops and goes back to the start.
Version: V0.8.5

I have a simple GPX file which loops through GG Park in SanFran.  If left alone it runs normally but never reaches the west side of the park because it is always interrupted by a "Server unstable, throttling API messages" event.  After this event the bot walks back to the start position of the GPX file and starts over.

It looks like the event is causing the "cancellation token" to be thrown in FarmPokestopsGPXTask.

With the frequency of the server going wacky, this is causing most GPX paths of any real length never to finish.  It would seem reasonable to continue the path for certain exceptions if the other bot functions continue to operate.

**Comment by theloser** [comment] 2016-08-11 10:37
Duplicate of #4813

**Closed** 2016-08-11 12:51 UTC
