### ISSUE TITLE
Bot using Ultra Ball on all Pokemons

### ISSUE THREAD

**Issue by UAVova** [NECROBOTIO/NecroBot#1883] opened 2016-08-01 19:51 UTC
I've set 
`"UseUltraBallAboveCp": 1000`
bot even on low level pokemons (1-3 lvl) bot is using Ultra Ball to catch them.

**Comment by recon88** [comment] 2016-08-01 19:55
Duplicate of #1746

**Closed by recon88** 2016-08-01 19:55 UTC
