### ISSUE TITLE
error appear from last release

### ISSUE THREAD

**Issue by ndut1986** [NECROBOTIO/NecroBot#1972] opened 2016-08-02 04:10 UTC
dunno what happen but suddenly it appear, yesterday it's not like this. encounter problem bla bla bla
[<a href="http://s86.photobucket.com/user/Ndut_Dani/media/SnapCrab_danindut%20-%20Runtime%2000000110%20-%20Lvl%2028%20Advance%20in%201h%2024m%20%20273968300000%20XP%20%20EXPH%2018427%20%20PH%2051%20%20Stardu_2016-8-2_10-57-5_zpsioi0b2cw.png.html" target="_blank"><img src="http://i86.photobucket.com/albums/k93/Ndut_Dani/SnapCrab_danindut%20-%20Runtime%2000000110%20-%20Lvl%2028%20Advance%20in%201h%2024m%20%20273968300000%20XP%20%20EXPH%2018427%20%20PH%2051%20%20Stardu_2016-8-2_10-57-5_zpsioi0b2cw.png" border="0" alt=" photo SnapCrab_danindut - Runtime 00000110 - Lvl 28 Advance in 1h 24m  273968300000 XP  EXPH 18427  PH 51  Stardu_2016-8-2_10-57-5_zpsioi0b2cw.png"/></a>](url)

**Comment by Energex22** [comment] 2016-08-02 08:07
yeah i started getting that, and now i am getting tons of red code, and then it restarts and repeats

**Comment by recon88** [comment] 2016-08-02 10:07
Duplicate of #1856

**Closed by recon88** 2016-08-02 10:07 UTC
Labels: duplicate
