### ISSUE TITLE
option to use an alternate sniper scanner

### ISSUE THREAD

**Issue by swc-tine** [NECROBOTIO/NecroBot#1861] opened 2016-08-01 18:40 UTC
maybe an option to use an alternate/more stable sniper scanner as skiplagged is having big issues?

**Comment by mrsean77** [comment] 2016-08-01 18:45
^
Any way to incorporate the option to use a local server like https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by recon88** [comment] 2016-08-01 18:47
Duplicate of #1842

**Closed by recon88** 2016-08-01 18:47 UTC
