### ISSUE TITLE
Trouble with google 2-step auth 

### ISSUE THREAD

**Issue by gingerpumpa** [NECROBOTIO/NecroBot#2186] opened 2016-08-02 19:14 UTC
I use a gmail account under a google domain , I must use 2 step authentication and I get created app passwords. But anyway so it will not work to get in , it went just fine before the app passwords. 

I have checked my Auth file many times and redownloaded a few times just to get a clear answer that im not doing anything wrong. I have also asked alot of people for help, but the only conclusion we have decided on to , is to post here about it. But I don't even know what to post here because i have no error message's or anything ! Just  what i describe. 

https://gyazo.com/4512a801affd2debcec4c6139860c02c

**Comment by recon88** [comment] 2016-08-02 19:17
Duplicate of #1900

**Closed by recon88** 2016-08-02 19:17 UTC
