### ISSUE TITLE
No Pokestops

### ISSUE THREAD

**Issue by dravenm4** [NECROBOTIO/NecroBot#2679] opened 2016-08-03 21:06 UTC
No usable Pokestops found, Maybe your search area is to small?

This is all I get at startup

**Comment by evansims** [comment] 2016-08-03 21:07
https://github.com/NECROBOTIO/NecroBot/issues/2645

**Comment by cyrus109** [comment] 2016-08-03 21:08
Same here. Something to change in config?

**Comment by IstenesImre** [comment] 2016-08-03 21:08
Yes.. "This conversation has been locked and limited to collaborators."

https://github.com/NECROBOTIO/NecroBot/compare/v0.6.4...master

**Comment by elmaarmut** [comment] 2016-08-03 21:08
Learn to read.

Why would yuo post this when #2645 already exists?

**Comment by nfettinger** [comment] 2016-08-03 21:17
Duplicate of #2654

**Closed by nfettinger** 2016-08-03 21:17 UTC
