### ISSUE TITLE
Weird going back when using GPX Pathing

### ISSUE THREAD

**Issue by jasio77** [NECROBOTIO/NecroBot#2233] opened 2016-08-02 20:40 UTC
My NecroBot is going back at some point and starting from default position again and again.
I'm using GPX Pathing. GPX file is from Resources in Wiki it's XP Farming, Central Park, Complete Loop 1.
![screenshot](https://cloud.githubusercontent.com/assets/20771421/17344316/edcaab68-5901-11e6-9686-f475f8dfb9d0.png)

**Comment by nfettinger** [comment] 2016-08-02 20:48
Is your instance getting hickups like throttling messages or connection issues?
Currently, the bot will always restart from the beginning of a GPX file every time that happens.

**Comment by jasio77** [comment] 2016-08-02 20:51
Yes he has sometimes hickups with API throttling. Is there method to avoid that?
I think it should continue from where bot was. It doesn't make any sense to start from beginning.

**Comment by nfettinger** [comment] 2016-08-02 20:52
Duplicate of #1856

**Closed** 2016-08-02 20:53 UTC
