### ISSUE TITLE
Always Evolve my pokemons with version 0.7.8

### ISSUE THREAD

**Issue by nalancer08** [NECROBOTIO/NecroBot#3587] opened 2016-08-09 05:06 UTC
I don´t want the Bot evolve my pokemons, but always do it, here is my JSON:

`{
  "TranslationLanguageCode": "es",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 1,
  "DetailedCountsBeforeRecycling": false,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 10000.0,
  "UpgradePokemonIvMinimum": 950.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 19.295646,
  "DefaultLongitude": -99.210662,
  "WalkingSpeedInKilometerPerHour": 31.0,
  "MaxSpawnLocationOffset": 10,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 9999999,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": false,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 999999,
  "KeepPokemonsThatCanEvolve": true,
  "KeepMinCp": 10,
  "KeepMinIvPercentage": 10.0,
  "KeepMinLvl": 3,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 5,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 100.0,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "MinPokeballsToSnipe": 200,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "TotalAmountOfPokeballsToKeep": 100,
  "TotalAmountOfPotionsToKeep": 20,
  "TotalAmountOfRevivesToKeep": 20,
  "TotalAmountOfBerriesToKeep": 35,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": false,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [],
  "PokemonsToIgnore": [
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo",
    "ekans",
    "geodude",
    "kakuna",
    "venonat",
    "paras",
    "caterpie",
    "weedle"
  ],
  "PokemonsTransferFilter": {},
  "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}`

**Comment by actislav** [comment] 2016-08-09 09:08
PokemonsToEvolve must be empty for this version

**Comment by nalancer08** [comment] 2016-08-09 10:26
But, is empty, i didn't add anything in this array

**Comment by nfettinger** [comment] 2016-08-09 14:18
Duplicate of #3548

**Closed by nfettinger** 2016-08-09 14:18 UTC
