### ISSUE TITLE
No usable pokestops found in your area, all the time!

### ISSUE THREAD

**Issue by feedbuck** [NECROBOTIO/NecroBot#2661] opened 2016-08-03 20:31 UTC
Can someone help me?

**Comment by murfman** [comment] 2016-08-03 20:31
same thing happening to me.

**Comment by chauhan-rahul** [comment] 2016-08-03 20:31
same here!!

**Comment by carlanivans** [comment] 2016-08-03 20:32
https://otakukart.com/animeblog/2016/08/03/minimum-scanning-time-doubled-see-effects/

**Comment by somani6** [comment] 2016-08-03 20:32
Please reffer to #2659

**Comment by nfettinger** [comment] 2016-08-03 20:32
Duplicate of #2645

**Closed by nfettinger** 2016-08-03 20:32 UTC
