### ISSUE TITLE
(NullReferceneException)Exception happening quite frequently

### ISSUE THREAD

**Issue by Sprinting** [NECROBOTIO/NecroBot#2550] opened 2016-08-03 15:54 UTC
![image](https://cloud.githubusercontent.com/assets/16353379/17372229/8fe0750e-59c0-11e6-88ef-874facaebfcb.png)
This has been happening quite frequently Idk what's the issue

**Comment by nfettinger** [comment] 2016-08-03 16:01
Duplicate of

**Closed** 2016-08-03 16:05 UTC

**Comment by Sprinting** [comment] 2016-08-03 16:13
How do I delete Issues? Sorry, I'm quite new
