### ISSUE TITLE
BOTS WORKS NOW BUT NO USABLE POKESTOP ERROR

### ISSUE THREAD

**Issue by teknojix** [NECROBOTIO/NecroBot#2645] opened 2016-08-03 20:01 UTC
I think ban wave is coming! :D

**Comment by Revoss** [comment] 2016-08-03 20:02
panic

**Comment by Gemori** [comment] 2016-08-03 20:02
Same here. Nothing but red lines.

**Comment by Sylencer90** [comment] 2016-08-03 20:02
yup down for me as wel, cant reach host or sth.

**Comment by onurakman** [comment] 2016-08-03 20:02
The hostname could not be parsed.

**Comment by nfettinger** [comment] 2016-08-03 20:03
This issue will remain open to fix the URL. All others should be marked as duplicate.

**Comment by svetlaan** [comment] 2016-08-03 20:04
Nintendo counter attack ?

**Comment by ClashofJeann** [comment] 2016-08-03 20:04
Pokemon go is down guys wait a few mins [http://ispokemongodownornot.com/](url)

**Comment by teknojix** [comment] 2016-08-03 20:05
No. I can login with nox. Problem isn't nintende servers.

**Comment by teknojix** [comment] 2016-08-03 20:05
All bots down

**Comment by Sylencer90** [comment] 2016-08-03 20:06
API update?

**Comment by ArThoX** [comment] 2016-08-03 20:06
`[20:59:58] Logging in using Google
[21:00:00] System.UriFormatException: URI non valide : Impossible d'analyser le nom d'hôte.
   à System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   à System.Uri..ctor(String uriString, UriKind uriKind)
   à System.Net.Http.HttpClient.CreateUri(String uri)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__1`1.MoveNext() dans ...\HttpClientExtensions.cs:ligne 61
-`

**Comment by GamingMaster777** [comment] 2016-08-03 20:06
i though i screwed up the config and got banned

**Comment by teknojix** [comment] 2016-08-03 20:06
BAN WILL COMING.

**Comment by theloser** [comment] 2016-08-03 20:06
WE ALL GOT BANNED. PANIC MODE.

Just calm down and chill, geez...

**Comment by ClashofJeann** [comment] 2016-08-03 20:07
Stop guys google login/ ptc logins are down sit and wait...

**Comment by Adriskye** [comment] 2016-08-03 20:08
[http://img.pixfans.com/2013/06/Pixfanschus-6.jpg](url)

**Comment by JEzuuuus** [comment] 2016-08-03 20:08
Ban Wave incoming.
Even if i would have reached level 40 tomorrow. 
was a nice time guys!!!! THX for support

**Comment by Venzhel** [comment] 2016-08-03 20:08
Banwave is just a rumor, after i got this error i tried to login with my phone and taking down 3 gyms and my account still doing fine. Chill

**Comment by colinodell** [comment] 2016-08-03 20:09
Stack trace:  
![image](https://cloud.githubusercontent.com/assets/202034/17380334/acb40258-5994-11e6-9cad-d5e01edf4a13.png)

**Comment by Sheetka** [comment] 2016-08-03 20:09
Venzhel, there seems to be an IP ban meaning your computer will be banned, not your phone

**Comment by MasterDomino** [comment] 2016-08-03 20:09
[*] naah i think its just some random instability.

**Comment by RentonXD** [comment] 2016-08-03 20:10
https://pbs.twimg.com/media/Co5eLQ_WIAAy6hd.jpg

Blocking GPS Spoofing is on agenda ;)

**Comment by Sheetka** [comment] 2016-08-03 20:10
Necronomicon - Today at 9:43 PM
@everyone If you're running a lot of accounts, Niantic has started limiting IPs so those accounts who have excessive requests / multiple accounts from the one location are temporarily blacklisted and receive empty map objects, which leads to what you see.
Necronomicon - Today at 10:01 PM
@everyone As a precautionary measure we recommend every Bot User to close down the Bot until we have checked what exactly is happening right now. Thanks

**Comment by MasterDomino** [comment] 2016-08-03 20:11
@Sheetka thanks :P

**Comment by zimmey** [comment] 2016-08-03 20:11
Invalid URI: The hostname could not be parsed.

Looks like the API likely used a hard coded hostname (which the dns is not resolving), this doesn't appear to indicate a block.

**Comment by MasterDomino** [comment] 2016-08-03 20:12
soo would normally changing that URI to proper work?

**Comment by ArThoX** [comment] 2016-08-03 20:13
Unnecessary rename

**Comment by MasterDomino** [comment] 2016-08-03 20:13
https://go.jooas.com/
unstable not caused by bans xD

**Comment by artuan00** [comment] 2016-08-03 20:13
**I shit myself when all the red lines started appearing lol. Glad its not just for me.**

**Comment by Venzhel** [comment] 2016-08-03 20:14
Nope, i use my laptop tethered by my phone, so both of them got an exact ip adress. I don't think it's ip ban or something like that :)

**Comment by zimmey** [comment] 2016-08-03 20:14
@MasterDomino hard to say, might be that the phones have the dns cached. Will likely be resolved shortly. Looks like a network issue.

**Comment by MasterDomino** [comment] 2016-08-03 20:14
@artuan00 aah soo you wont be alone when you get fucked xD

**Comment by artuan00** [comment] 2016-08-03 20:15
@MasterDomino <.< haha

**Comment by mik5u** [comment] 2016-08-03 20:16
works fine with my phone (andrioid)

**Comment by MasterDomino** [comment] 2016-08-03 20:16
@zimmey sorry because im not that good in this whole networking thing whats the difference between URI and dns and couldnt you use DNS soo it would always work?

**Comment by facinick** [comment] 2016-08-03 20:18
when will this be corrected ?

**Comment by 3h3c** [comment] 2016-08-03 20:18
it works now

**Comment by yoshi2323** [comment] 2016-08-03 20:18
Since ~18 hours ago, all my 200+ bots go into "No useable PokeStop found" or Softban Loop Mode within 90 seconds after start.

Seems like niantic has but a limit on connections per ip...

**Comment by mik5u** [comment] 2016-08-03 20:19
trainerclub is offline and google down

**Comment by spiritpaze** [comment] 2016-08-03 20:19
No usable pokestops found in your area. I did not change anything in config, what happened?

**Comment by YangSkyL** [comment] 2016-08-03 20:19
It's working now

**Comment by Adriskye** [comment] 2016-08-03 20:19
just wait till all fixed

**Comment by ClashofJeann** [comment] 2016-08-03 20:19
GOOGLE LOGIN IS OK/ PTC IS DOWN

**Comment by Venzhel** [comment] 2016-08-03 20:20
200+ bot @@

**Comment by facinick** [comment] 2016-08-03 20:20
no pokestops found in your area?

**Comment by 3h3c** [comment] 2016-08-03 20:20
login with google working, but no pokestops available

**Comment by artuan00** [comment] 2016-08-03 20:20
PTC is working. No PokeStops found.

**Comment by spiritpaze** [comment] 2016-08-03 20:20
Same

**Comment by Autobotuser** [comment] 2016-08-03 20:20
same here

**Comment by JSBeard** [comment] 2016-08-03 20:20
I got the same red text as everyone else an hour ago, but it kept playing for 30mins afterwards, but then had a squirtle flee on the first ball and then notification of a possible softban at a Pokestop. It tried the 45 times, went to the next stop and got the same no items looted possible softban and started to try 45 more times.

**Comment by Autobotuser** [comment] 2016-08-03 20:21
Android working fine thou

**Comment by pokemongofan** [comment] 2016-08-03 20:21
poke stop not found
phone works

**Comment by nfettinger** [comment] 2016-08-03 20:22
You can still use the accounts with your devices.

**Closed** 2016-08-07 12:20 UTC
Labels: bug, ready, Urgent
