### ISSUE TITLE
All Pokemons got transferred when KeepMinCp is higher than Pokemon, Duplicated too!!! 

### ISSUE THREAD

**Issue by Korni1987** [NECROBOTIO/NecroBot#4407] opened 2016-08-10 08:56 UTC
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Your config.json
```
your config here
```

### Other Information
Version:
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by necr-0** [comment] 2016-08-10 08:57
You understand the template is there to use right?
Edit your post and use it.

**Comment by Kjewn** [comment] 2016-08-10 09:00
Rip settings

**Comment by Snake87r** [comment] 2016-08-10 09:01
I have the same problem and resolved:
The cause is simple, the config.json is overwritten with a new one (same go for the auth.json), you have simply to adjust the config.json with the value you prefer..

**Comment by manhdinh** [comment] 2016-08-10 09:01
When i run necroot 0.8.4 few minutes ago, everything ok, but after few pokestop, my account is banned. And when i use necrobot 0.8.5, this is the issue : http://prntscr.com/c3viwj .
I use default setting 
[config.txt](https://github.com/NECROBOTIO/NecroBot/files/410644/config.txt)

**Comment by Kjewn** [comment] 2016-08-10 09:03
"KeepMinCp": 1250,
  "KeepMinIvPercentage": 90.0,

"KeepMinDuplicatePokemon": 0,

thats not weird, it transfer everything...

**Comment by Quendi6** [comment] 2016-08-10 09:03
bad post but real issue. Since 0.8.5 pokemon are transferred. Seems to work like when "TransferWeakPokemon" is true. Also I lost all my configuration when update, like my position and my auth, obviously...

**Comment by Kjewn** [comment] 2016-08-10 09:03
Also,   "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

**Comment by Kjewn** [comment] 2016-08-10 09:04
@Quendi6 he does not have that set it seems.

**Comment by Quendi6** [comment] 2016-08-10 09:04
@Kjewn right

**Comment by Quendi6** [comment] 2016-08-10 09:12
"KeepMinDuplicatePokemon":  -> change 0 to desired value

**Comment by Korni1987** [comment] 2016-08-10 09:17
"KeepMinDuplicatePokemon is set to one. I understand to use it.
weak pokemon is 0. keep min pokemon is 1000 but he transfer all

**Comment by Decubitus** [comment] 2016-08-10 09:17
"KeepMinDuplicatePokemon": 1,

**Comment by Korni1987** [comment] 2016-08-10 09:19
i see, why its now set to 0?update before it wasnt.

**Comment by Quendi6** [comment] 2016-08-10 09:21
i think it's a mistake, change has been made on config.json, like humanized throws, snipe feeders...

**Comment by Decubitus** [comment] 2016-08-10 09:23
Whats the Script name 
Nidoran Male
Nidoran Fem
Don't work anyway i tried

**Comment by theloser** [comment] 2016-08-10 09:49
nidoranmale and nidoranfemale
This is a config issue. Please go to [Discord](https://discord.gg/VXKxNFr) and ask for help.

**Closed** 2016-08-10 10:46 UTC
