### ISSUE TITLE
No usable Pokestops

### ISSUE THREAD

**Issue by txisme** [NECROBOTIO/NecroBot#2687] opened 2016-08-03 21:27 UTC
After last update (0.6.4) it started appear the message:

"(ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?"

So now my BOT is just in a loop. Whats wrong? My maximum distance is the default one, i tried already to maximize it and still the same error, even in different initial positions.

**Comment by Sadfaffel** [comment] 2016-08-03 21:28
https://github.com/NECROBOTIO/NecroBot/issues/2645

**Comment by Cuuup** [comment] 2016-08-03 21:29
Duplicate of #2654

**Comment by artuan00** [comment] 2016-08-03 21:30
#2645

**Comment by nfettinger** [comment] 2016-08-03 21:42
Duplicate of #2645

**Closed by nfettinger** 2016-08-03 21:42 UTC
