### ISSUE TITLE
Pokemon on PokemonsToEvolve list don't transfer, even with KeepPokemonThatCanEvolve set to false

### ISSUE THREAD

**Issue by Blemmer123** [NECROBOTIO/NecroBot#2227] opened 2016-08-02 20:27 UTC
I had the same problem with some of my pokemon. I had the following settings:

"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": false,
"EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
"KeepPokemonsThatCanEvolve": false,
"KeepMinCp": 2000,
"KeepMinIvPercentage": 95.0,
"PrioritizeIvOverCp": true,
"KeepMinDuplicatePokemon": 1,
"TransferWeakPokemon": false,
"TransferDuplicatePokemon": true,
"TransferDuplicatePokemonOnCapture": false,
"UsePokemonToNotCatchFilter": false,
"UsePokemonSniperFilterOnly": false,

With these settings I keep 1 of every type AND any pokemon above 95 IV OR above 2000 IV. For some reason though, mostly low level pokemon (rattatas/pidgeys/weedles) did not transfer. These were not on the "PokemonsNotToTransfer" list.

I found a fix: It seems that the bot didnt transfer the pokemon that were on the PokemonsToEvolve list, even though KeepPokemonThatCanEvolve was set to false. SO I emptied the list, and from that moment on all pokemon got transferred again.

I dont know how to fix this in the code, but I figured this could help the developers fixing this bug.

**Comment by recon88** [comment] 2016-08-02 20:31
Possible duplicate of #2187

**Closed by recon88** 2016-08-02 20:31 UTC
