### ISSUE TITLE
Change KeepDuplicatePokemons to NumberToKeepOfEachPokemon and set default to 1

### ISSUE THREAD

**Issue by PokemasterMike** [NECROBOTIO/NecroBot#2442] opened 2016-08-03 09:21 UTC
change the name of the setting and make it so it does what it says. the current way, the bot keeps one of each pokemon (why would you ever want to do that ???) otherwise have to specifically ignore them (so if you want a clean pokeinventory you have to manually ignore like 100 pokemon... really ???)

**Comment by emwedk** [comment] 2016-08-03 09:24
you want to have 1 of each pokemon when you only have 250 slots in your inventory 
the math says -

145 pokemons * 2 = 290

it doesnt add up - which is why most people use the Section
  "PokemonsTransferFilter": {
and alter it for the pokemons they wanna shave multiple of :)

**Comment by PokemasterMike** [comment] 2016-08-03 09:28
actually i want to have 0 of every pokemon except for the ones i specifically exclude (via other settings) but i cant accomplish that in the current version (because it keeps 1 anyway). having the variable renamed and set to 1 would change the default behavior but make it easy to set it to 0

**Comment by PokemasterMike** [comment] 2016-08-03 09:29
also pokemontransfer filter and all the stuff related to is buggy as hell as of now (see other issues)

**Comment by Majamulli** [comment] 2016-08-03 09:35
So I am understanding this right? Until 0.6.0 the KeepMinDuplicatePokemon = 1 meant that you keep 1 of each pokemon and since 0.6.0 it means that it keeps 2 of each pokemon? If yes then this really should be changed to something like NumberOfEachPokemonToKeep like suggested.

**Comment by Caliboss** [comment] 2016-08-03 09:38
so your saying keep 0 duplicates will keep 1 of each right?

**Comment by noodle-** [comment] 2016-08-03 09:39
@emwedk If you set ```KeepDuplicatePokemons``` to 0 so it only keeps one of each pokemon instead of one duplicate pair of each pokemon. This is the default value for this setting but it might still be set to 1 on your end.

The default value was 1 and back then ```KeepDuplicatePokemons``` functioned the same way as ```KeepDuplicatePokemons``` set to 0 functions now, but ```KeepDuplicatePokemons``` got fixed. Which may cause some confusion.

@Majamulli
>So I am understanding this right? Until 0.6.0 the KeepMinDuplicatePokemon = 1 meant that you keep 1 of each pokemon and since 0.6.0 it means that it keeps 2 of each pokemon?

It doesn't really need a name change, it does exactly as it says, it keeps one duplicate of every pokemon if you set it to 1, and no duplicates (so just one) if you set it to none.

@PokemasterMike That's a valid use case. :thumbsup:

@Caliboss Yes.

**Comment by emwedk** [comment] 2016-08-03 09:46
on my end, it doesnt behave like that.

[config.json](http://emwe.dk/config.json)
[dump](http://emwe.dk/NecroBot-PokeBagStats-2016-08-03-11.csv)
Search for ratticate, beedrill, pidgeot, fearow <- in the dump

**Comment by Majamulli** [comment] 2016-08-03 09:47
@noodle- it's true that it does exactly what it says - BUT this option existed before 0.6.0 and did something ELSE. So people are used to it working differently and many people are not willing to just change it to 0 to try what happens because they know that setting it to 1 will keep 1 of each pokemon. That's how it always worked.
This is why I suggest changing the name.

**Comment by noodle-** [comment] 2016-08-03 09:55
@Majumulli True. But changing the name now would only mess it up more. It now does what it says it does.

If you want to change the name **and way of functioning** to NumberToKeepOfEachPokemon I will lose pretty much all of my pokemons because I have KeepDuplicatePokemons set to 0 and settings don't get changed on update to default values. Default values are only used if there is no such setting in your config file.

**Comment by noodle-** [comment] 2016-08-03 09:58
@emwedk What the ...

Does ```KeepMinDuplicatePokemon``` function differently when set global as opposed to those per pokemon filters?

**Comment by emwedk** [comment] 2016-08-03 10:02
@noodle not entirely sure since in Global, it's set to 0, but in Locals(individual Pokemons) 
ALL pokemons is listed, and set differently for each pokemon.
some at 0, which results in 0 pokemon

i really don't dare to do 
KeepMinDuplicatePokemon to 0
in Globals to test it lol

**Comment by PokemasterMike** [comment] 2016-08-03 10:03
@noodle- thats why i suggested to make default to 1

**Closed** 2016-08-03 10:03 UTC

**Comment by PokemasterMike** [comment] 2016-08-03 10:08
@Wcidd  why was this closed ? either revert back to old behavior or give a possiblity to make it manually do that...

**Comment by noodle-** [comment] 2016-08-03 10:08
@PokemasterMike That does not work, settings don't override if they're set to something else already. The default value is only for people who don't have have the setting in their config yet.

@Wcidd Why would you close this, there's clearly something wrong. If you don't see that at least leave it open as feature request for @PokemasterMike .

**Comment by PokemasterMike** [comment] 2016-08-03 10:11
@noodle- if you remove the old setting and make a new one, it should automatically be set to a default value

**Comment by noodle-** [comment] 2016-08-03 10:14
@PokemasterMike oh, I didn't think about that. You're probably right..

**Comment by noodle-** [comment] 2016-08-03 10:30
@PokemasterMike You'll probably have to create a new issue/featurerequest because @Wcidd aka Mr Triggerhappy issue closer [doesn't usually re-open any issues, even if they're valid.](https://github.com/NECROBOTIO/NecroBot/issues/2342)

@emwedk This is definitely something that should be tested though.

**Comment by noodle-** [comment] 2016-08-03 10:47
@Majamulli 
>Edit: just look at whats happening all around. Just now a new issue was created where a user asks how to keep 1 of each pokemon and someone here "helps" them by saying he needs to put KeepMinDuplicatePokemon to 1. It is not known properly....
And I just read what @emwedk wrote so it seems like there's really something wrong.

The people helping are probably used to the old behaviour & haven't seen the change or read the wiki since.

But yea there's definitely something wrong with KeepMinDuplicatePokemon global/local. I can't be bothered to create a new issue though as it'll just get closed for no reason and spamming issues really shouldn't be the way to go...

**Comment by PokemasterMike** [comment] 2016-08-03 18:35
has anybode else made a new issue/request ? havent been online the last 8 hours... if not ill open one again with feature request

**Comment by noodle-** [comment] 2016-08-03 19:34
@PokemasterMike Didn't make a new issue but apparantly KeepMinDuplicatePokemon works the same way it used to, again. So for your use case you could set KeepMinDuplicatePokemon to 0.

I'd recommend testing it with a dummy account. Set TransferDuplicatePokemon to false for a while and then set it back to true and look at what's happening.
