### ISSUE TITLE
Is your maximum distance too small?

### ISSUE THREAD

**Issue by korkor1** [NECROBOTIO/NecroBot#2668] opened 2016-08-03 20:44 UTC
This message appears constantly

**Comment by nfettinger** [comment] 2016-08-03 20:44
Duplicate of #2645

**Comment by wowstin** [comment] 2016-08-03 20:45
They are aware, it's an issue with map loading, imo it's niantic attempt against botting idk at all tho just wait for update

**Closed by nfettinger** 2016-08-03 20:44 UTC
