### ISSUE TITLE
item specification.

### ISSUE THREAD

**Issue by cutestguy** [NECROBOTIO/NecroBot#2115] opened 2016-08-02 16:53 UTC
can you put back the feature where u can specify how much pokeball or ultraball to save also the potion if i want only max potion and hyper to save and recycle others.. thanks..

**Comment by theloser** [comment] 2016-08-02 16:56
That has been discussed so many times: the way it now works will guarantee that you always keep the best pokeballs and potions you will find and only recycle lesser ones.

**Comment by recon88** [comment] 2016-08-02 16:57
Duplicate of #1702

**Closed by recon88** 2016-08-02 16:57 UTC
