### ISSUE TITLE
[Suggestion] PokemonsTransferFilter, add setting to keep enough pokemon to match candies

### ISSUE THREAD

**Issue by AVellucci** [NECROBOTIO/NecroBot#1981] opened 2016-08-02 04:53 UTC
A setting to keep enough pokemon to use all candies, example: If I have 120 Pidgey candies, using this new setting it will transfer all but 12 Pidgey so that I can evolve them at my own discretion with either Necrobot or myself.
This could be a boolean setting or a setting that lets you input the starting candies and adds +3 on each capture and +1 on each release then divides the number by the evolve cost and uses that integer to set the amount to keep.

**Comment by Squirrel3098** [comment] 2016-08-02 05:10
could be a cool feature. For now you could just set it to keep a number of pidgey's (if you have  a bag upgrade) just set it to like say 30 pidgeys to keep and add it to the list to not evolve. then let it farm hundreds while keeping the 30 for your lucky egg.

**Comment by AVellucci** [comment] 2016-08-02 05:26
I wouldn't keep just 30, I can manually evolve 65 pokemon if I do it myself, if I were to lucky egg using the bot I'd definitely do it with a much larger amount of stacked pokemon, as I'm sure it could probably evolve much quicker. But this would be a nice feature to have instead of having to add rule after rule to try and achieve this.

**Comment by nfettinger** [comment] 2016-08-02 12:51
This config setting does just what you are asking!
KeepPokemonsThatCanEvolve

**Comment by AVellucci** [comment] 2016-08-02 13:41
unless I have it set incorrectly, it will keep all the potential evolvable pokemon, say I can evolve only 2 pidgey it will keep all the pidgey that are found for me. It could be I might have another config setting thats breaking this but at this time it doesn't seem to do what I'm asking for.

**Comment by nfettinger** [comment] 2016-08-03 13:05
This is a duplicate of #2001

**Closed by nfettinger** 2016-08-03 13:05 UTC
Labels: enhancement, ready
