### ISSUE TITLE
[BUG] GPX path issue?

### ISSUE THREAD

**Issue by BourbonCrow** [NECROBOTIO/NecroBot#1951] opened 2016-08-02 01:32 UTC
http://imgur.com/a/1UrmD

an image of the issue, it happens EVERY lap he does I have even tried to remake the GPX pathing.
Below are the settings i believe is related to this
```
"UseGpxPathing": true,
"DisableHumanWalking": false,
"MaxTravelDistanceInMeters": 400000,
```

**Comment by BourbonCrow** [comment] 2016-08-02 04:37
I think i found the reason..
[06:35:56] (ERROR) Niantic Servers unstable, throttling API Calls.
everytime that happends he start walking back to first waypoint skipping the once ahead..
maybe if there is a way to code the bot so he remembers where he last was when that happends and continue from there

**Comment by recon88** [comment] 2016-08-02 10:06
Duplicate of #1856

**Closed by recon88** 2016-08-02 10:06 UTC
