### ISSUE TITLE
No usable Pokestops after update?

### ISSUE THREAD

**Issue by Arhtex** [NECROBOTIO/NecroBot#2685] opened 2016-08-03 21:18 UTC
I'm receiving this error consistently with new update. The bot won't acknowledge coordinates. any one else have this issue?

**Comment by nfettinger** [comment] 2016-08-03 21:18
Duplicate of #2654

**Comment by PewSztiePoll** [comment] 2016-08-03 21:18
Here's some guys are comming to tell you that your issue is duplicate.

**Closed by nfettinger** 2016-08-03 21:18 UTC
