### ISSUE TITLE
no nearby pokestops ..??

### ISSUE THREAD

**Issue by urhit45** [NECROBOTIO/NecroBot#2670] opened 2016-08-03 20:48 UTC

**Comment by Jurplez** [comment] 2016-08-03 20:49
Everyone gets this error now

**Comment by ifbatmanwasreal** [comment] 2016-08-03 20:50
CAN YOU READ

**Comment by Messepark** [comment] 2016-08-03 20:50
#2645

**Comment by nfettinger** [comment] 2016-08-03 20:51
Duplicate of #2645

**Closed by nfettinger** 2016-08-03 20:51 UTC

**Comment by Lefighter** [comment] 2016-08-03 20:58
yep no pokestop LUL
