### ISSUE TITLE
mailware detect by KIS 2016

### ISSUE THREAD

**Issue by sounddanezzboiz** [NECROBOTIO/NecroBot#3822] opened 2016-08-09 12:59 UTC
i use necrobot in about 3 hours and till the my Kaspersky detect necrobot is mailicius and deleted????

**Comment by RiPPERD** [comment] 2016-08-09 13:03
its due to the nature of the bot... hammering the data with packets back and forth and api calls etc... just ignore it or disable it... get a better anti virus like ESET 

please close this case as this is not a bug or problem with the bot

**Closed** 2016-08-09 13:05 UTC
