### ISSUE TITLE
Another wrong transfer it seems, not settings related

### ISSUE THREAD

**Issue by ThomasSRL** [NECROBOTIO/NecroBot#3966] opened 2016-08-09 17:01 UTC
Hi,

My bot just transfered a snorlax with 1764CB 94% IV for a Snorlax with 2512CB 81% IV, while settings are set to prioritise IV over CB.
For other pokemon it does prioritise the IV (example just before the Snorlax it transfered a Magicarp 127CB 64% for one with 11CB 96%.
Picture:
http://oi64.tinypic.com/14cfe2o.jpg

My config:
http://pastebin.com/tZsKWngr

I'm unsure why this happened tbh?

Any suggestions are welcome..

**Comment by Caydenz** [comment] 2016-08-09 17:05
"KeepMinCp": 2500,
  "KeepMinIvPercentage": 95.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",

CP is below 2500 and IV is below 95%. That's why it was transferred. The second one's CP is above 2500 and was kept.

**Comment by theloser** [comment] 2016-08-09 17:05
Hm, I am not sure: you also have the following in your config:
 "KeepMinCp": 2500,
  "KeepMinIvPercentage": 95.0,
The Snorlax which has been transferred does not fit any of these, but the "best" Snorlax does (CP > 2500).

**Comment by ThomasSRL** [comment] 2016-08-09 17:08
Thanks both, @theloser @Caydenz 
So if the lower CB snorlax was 95+ it would have kept it?
Just that I've been using these settings for a long time and never noticed something like this...

**Comment by theloser** [comment] 2016-08-09 17:12
> So if the lower CB snorlax was 95+ it would have kept it?
Yes.

**Comment by NunoAG** [comment] 2016-08-09 17:13
Snorlax 1:
- 1764 > 2500: false
- 94 > 95: false

Snorlax 2:
- 2512 > 2500: true
- 81 > 95: false

Because "KeepMinOperator" is set to "or" it only takes one clause to be true to keep the pokemon.
Snorlax 1 doesn't fit you configs

**Comment by nfettinger** [comment] 2016-08-09 18:32
Please use the Discord chat rooms for general help.
If there is a bug, this is duplicate of #3338

**Closed by nfettinger** 2016-08-09 18:32 UTC
