### ISSUE TITLE
[Feature Request] Use Great/Ultra Balls for certain Pokemon TYPES

### ISSUE THREAD

**Issue by joshownz98** [NECROBOTIO/NecroBot#2029] opened 2016-08-02 11:03 UTC
Currently you can only set masterballs to be used for certain pokemon, but I feel there should be option for great and ultra ball too. For example, necrobot will use ultra balls for all Dragonites, no matter how low the CP is.

**Comment by recon88** [comment] 2016-08-02 11:08
Duplicate of #1745

**Closed by recon88** 2016-08-02 11:08 UTC
