### ISSUE TITLE
Current Bug (No Pokestops) - BlueStacks App works fine

### ISSUE THREAD

**Issue by RentonXD** [NECROBOTIO/NecroBot#2680] opened 2016-08-03 21:08 UTC
As the title says Pkmn Go on Bluestacks works fine and you see an can use pokestops there as normal. 

Maybe an API Issue?

**Comment by IstenesImre** [comment] 2016-08-03 21:10
Yep

**Comment by piratefinn** [comment] 2016-08-03 21:10
Definitely API, see the current commits to the project for the next update.

**Comment by Corgano** [comment] 2016-08-03 21:11
Duplicate of #2645

**Comment by IstenesImre** [comment] 2016-08-03 21:13
You are duplicated.

**Comment by RentonXD** [comment] 2016-08-03 21:14
it's no duplicate because this info isn't given there... <.<

**Comment by nfettinger** [comment] 2016-08-03 21:17
Duplicate of #2654

**Closed by nfettinger** 2016-08-03 21:17 UTC
