### ISSUE TITLE
Attention No usable pokestops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by Toekan1** [NECROBOTIO/NecroBot#2683] opened 2016-08-03 21:12 UTC
Hey guys,

I really hope you can help me. Since 1 hour, it says :'Attention No usable pokestops found in your area. Is your maximum distance too small? I cant solve this issue. I tried multiple latitudes and longitudes. If someone could help me out, i would really appreciate it!

Thanks in advance

**Comment by razzzzamatazz** [comment] 2016-08-03 21:13
duplicate of #2645

**Comment by elmaarmut** [comment] 2016-08-03 21:13
Learn to read.

Why would you post this when #2645 already exists?

**Comment by head0r** [comment] 2016-08-03 21:14
[NicCage: "You don*t saaaaay"]

**Comment by nfettinger** [comment] 2016-08-03 21:17
Duplicate of #2654

**Closed by nfettinger** 2016-08-03 21:17 UTC

**Comment by 17yongga** [comment] 2016-08-09 05:15
VPN would fix your problem.
