### ISSUE TITLE
<ERROR> Unknown Telegram Error occured.

### ISSUE THREAD

**Issue by WaterFl0ws** [NECROBOTIO/NecroBot#5392] opened 2016-08-12 07:08 UTC
<ERROR> Unknown Telegram Error occured. on Necrobot version 0.8.6
Cant talk with bot anymore.
Tried to "null" password (without quote), also still getting error.
I check on BotFather on Telegram, there isnt password setting.
Anyone can help?

**Comment by Dexter145** [comment] 2016-08-12 07:12
Same here.

**Comment by theloser** [comment] 2016-08-12 07:15
I tested some pre-0.8.6 source code versions and Telegram seems to be broken atm. Please wait until it'll be fixed. Has nothing to do with the TelegramPassword option.

**Comment by WaterFl0ws** [comment] 2016-08-12 07:22
thanks, will do

**Comment by ftc2** [comment] 2016-08-12 07:27
@theloser actually, i just re-tested with 0.8.5 release, and it's working fine with telegram.
it is clearly an issue with 0.8.6 necro.

**Comment by CrispyBaconUk** [comment] 2016-08-12 07:50
The password setting is probably in relation to the 2 step authentication which you can setup.

**Comment by theloser** [comment] 2016-08-12 07:56
@ftc2 Yes, Telegram works in 0.8.5! It broke when there were some changes in the .NET framework between 0.8.5 and 0.8.6

@CrispyBaconUk The password function allows only user who know the password for your bots to send commands! Works like this:

Instead of just 
```
/top
```
you will have to send
```
/login <yourpassword> <-- this authorizes you for 5 minutes to send command to your bot
/top
```
Hope that helps.

**Comment by theloser** [comment] 2016-08-12 11:41
Also duplicate of #5323

**Closed** 2016-08-12 11:46 UTC
