### ISSUE TITLE
Bot "Walks" with double Speed

### ISSUE THREAD

**Issue by xXMrGXx** [NECROBOTIO/NecroBot#4465] opened 2016-08-10 10:21 UTC
### Expected Behavior
"WalkingSpeedInKilometerPerHour": 10.0,
(10km/h)

### Actual Behavior
69 meters in 13 seconds (The CMD window says that) -> 5,30769231 m/s -> about 20 km/h

### Your config.json
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": false,
  "TransferConfigAndAuthOnUpdate": false,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": false,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "cp",
  "UpgradePokemonCpMinimum": 3000.0,
  "UpgradePokemonIvMinimum": 100.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": true,
  "DefaultLatitude": 35.6895,
  "DefaultLongitude": 139.6917,
  "WalkingSpeedInKilometerPerHour": 10.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 250,
  "DelayBetweenPokemonCatch": 250,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 85.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 1150,
  "KeepMinIvPercentage": 98.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": false,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "minEggKmForLimitedIncubators": 2,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "and",
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": false,
  "GetOnlyVerifiedSniperInfoFromPokezz": false,
  "GetSniperInfoFromPokeSnipers": false,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 100,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 30000,
  "SnipingScanOffset": 0.013,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": true,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": true,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 15,
  "MaxTravelDistanceInMeters": 9000,
  "TotalAmountOfPokeballsToKeep": 110,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1550,
  "UseMasterBallAboveCp": 2900,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": false,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": true,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": null,
  "PokemonsToIgnore": [
    "bulbasaur",
    "ivysaur",
    "charmander",
    "charmeleon",
    "squirtle",
    "wartortle",
    "metapod",
    "butterfree",
    "kakuna",
    "beedrill",
    "pidgeotto",
    "pidgeot",
    "raticate",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "pikachu",
    "raichu",
    "sandshrew",
    "sandslash",
    "nidorina",
    "nidoqueen",
    "nidorino",
    "nidoking",
    "clefairy",
    "clefable",
    "vulpix",
    "ninetales",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "paras",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "persian",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "growlithe",
    "arcanine",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "machop",
    "machoke",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "ponyta",
    "rapidash",
    "slowpoke",
    "slowbro",
    "magnemite",
    "magneton",
    "doduo",
    "dodrio",
    "seel",
    "dewgong",
    "grimer",
    "muk",
    "shellder",
    "cloyster",
    "gastly",
    "haunter",
    "gengar",
    "drowzee",
    "hypno",
    "krabby",
    "kingler",
    "voltorb",
    "electrode",
    "exeggcute",
    "cubone",
    "marowak",
    "hitmonlee",
    "hitmonchan",
    "lickitung",
    "koffing",
    "weezing",
    "chansey",
    "tangela",
    "kangaskhan",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "jynx",
    "electabuzz",
    "magmar",
    "pinsir",
    "tauros",
    "magikarp",
    "lapras",
    "ditto",
    "eevee",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "omanyte",
    "omastar",
    "aerodactyl",
    "dratini",
    "dragonair"
  ],
  "PokemonsTransferFilter": {},
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 40.712784,
        "Longitude": -74.005941
      },
      {
        "Latitude": 52.370216,
        "Longitude": 4.895168
      },
      {
        "Latitude": 59.329323,
        "Longitude": 18.068581
      },
      {
        "Latitude": 22.27972,
        "Longitude": 114.158091
      },
      {
        "Latitude": 48.856614,
        "Longitude": 2.352222
      },
      {
        "Latitude": -33.86882,
        "Longitude": 151.209296
      },
      {
        "Latitude": 37.77493,
        "Longitude": -122.419416
      },
      {
        "Latitude": 35.689488,
        "Longitude": 139.691706
      },
      {
        "Latitude": 52.520007,
        "Longitude": 13.404954
      },
      {
        "Latitude": 34.052234,
        "Longitude": -118.243685
      },
      {
        "Latitude": 38.907192,
        "Longitude": -77.036871
      },
      {
        "Latitude": 39.952584,
        "Longitude": -75.165222
      },
      {
        "Latitude": 51.507351,
        "Longitude": -0.127758
      }
    ],
    "Pokemon": [
      "caterpie",
      "rattata",
      "weedle",
      "pidgey",
      "snorlax",
      "golem",
      "exeggutor",
      "kabuto",
      "kabutops",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

### Steps to Reproduce
Setup Speed -> Look in CMD Window -> Calculate Speed 

### Other Information
Version: 0.8.5
Windows Version: Windows 7

**Comment by necr-0** [comment] 2016-08-10 10:26
> "DisableHumanWalking": true,

Set it to _false_.

**Comment by WishmasterNano** [comment] 2016-08-10 10:29
checked it, its the same for me, calculated speed is way higher than the configurated

`"DisableHumanWalking":` is on `false`

**Comment by ausscheider** [comment] 2016-08-10 11:46
This are not kmh
This are Meter per second
Write 2.7 when you want Use 10 km/h

**Comment by weedorbeat** [comment] 2016-08-10 11:50
Its not a bug... just a presentation problem in log output, look at #3993

**Comment by nfettinger** [comment] 2016-08-10 12:58
Closing Duplicate

**Closed by nfettinger** 2016-08-10 12:58 UTC
