### ISSUE TITLE
Log File Disable

### ISSUE THREAD

**Issue by nisanb** [NECROBOTIO/NecroBot#2010] opened 2016-08-02 08:11 UTC
Hi!
I'd appreciate an option to disable all log files writings (I think the issue causing crashes when multiple instances are opened)

Thanks ;)

**Comment by streppelchen** [comment] 2016-08-02 08:31
are you running multiple instances from the same folder? 
normally the logfiles are no problem, and seperate instances should be run from different folders.

**Comment by nisanb** [comment] 2016-08-02 08:45
I'm running instances from separate folders

**Comment by recon88** [comment] 2016-08-02 10:19
Duplicate of #1917

**Closed by recon88** 2016-08-02 10:19 UTC
