### ISSUE TITLE
School managed google e-mail having troubles logging in

### ISSUE THREAD

**Issue by Kemosabe9** [NECROBOTIO/NecroBot#2765] opened 2016-08-07 13:34 UTC
Hey, I am having troubles logging into my google account using my.edu email managed by my school. Usually when I login to pokemon go i am redirected to my schools portal to log in there with my netID and password. 
Whenever I run the necro bot client, it always thinks I have 2-step auth on even when I turn it off and it redirects me to the google website to make an app password. Even when I make an app password and put it in the auth.json it doesn't work. 
I tried using the bot on my PTC alt account and it works fine.
I was wondering what useProxy was for in the auth.json. Maybe I need to use those settings to log in through my schools portal? Not sure exactly how it works but I would appreciate some help logging into my account. I am sure other people have this problem when trying to log in with a google account managed by a different domain. Thank you.

**Comment by erichuxuchen** [comment] 2016-08-07 13:38
Same problem, I'm crazy as well

**Comment by BlauDev** [comment] 2016-08-07 13:40
Duplicate of #2764

**Closed** 2016-08-08 14:02 UTC
