### ISSUE TITLE
New version of bot detected as virus?

### ISSUE THREAD

**Issue by harmbasi** [NECROBOTIO/NecroBot#4869] opened 2016-08-11 00:45 UTC
Anyone else getting this? I've been fine up until now, the new version of the bot 0.8. 5 is being detected as a virus PDM:Trojan.Win32.Bazon.a. We know the source code is here, but what about the release packages?

**Comment by theloser** [comment] 2016-08-11 00:49
Duplicate of #4870 

Kaspersky is not the only one who flagged NecroBot as "malicious" in the past few days. Pretty sure it's a "false positive", but if you don't trust it, then don't use it.

**Comment by Oolaruu** [comment] 2016-08-11 00:55
Kaspersky 	UDS:DangerousObject.Multi.Generic 	20160810

**Comment by djdookie** [comment] 2016-08-11 01:02
If you don't trust it, just have a look at the source code. ;)

**Comment by Oolaruu** [comment] 2016-08-11 01:26
@djdookie Where I said I don't trust it? 
I just submitted the latest .exe Necrobot into totalvirus website and found that too.
So confirmed, false positive or not, there are 2 differents "things" flaged as not normal.

**Comment by norecha** [comment] 2016-08-11 01:34
@djdookie stop pasting same shit everywhere. correct one would be "if you dont trust, look at the source code AND build it yourself". 

There is no guarantee release.zip is actually built from the source code. you can put whatever .exe you want there. I'm not saying exe has malicious code; but technically you can put one

**Comment by djdookie** [comment] 2016-08-11 01:55
@norecha Stay cool and stop raging pls! I didn't post "shit everywhere", I just gave the advise that NecroBot is open source, so everyone is able to see what happens inside. Of course you have to compile it yourself, otherwise you would execute the code you checked.
I am thankful for the advise that some scanners trigger some signature on NecroBot, but I am also quite sure it's false positive.
And please search before you duplicate issues!

**Comment by akmalbaik** [comment] 2016-08-11 02:55
hi, is there any workaround to this issue currently? i have disabled my pc's window security like window defender and also antivirus but yet again the release.zip gets deleted once i have downloaded it..not sure what else am i missing..any advise please? on my other pc its fine..this happened probably after i just updated my windows

**Comment by Oolaruu** [comment] 2016-08-11 03:36
Well, latest compile from latest commit, show again a false positive.

**Comment by nfettinger** [comment] 2016-08-11 13:17
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Closed by nfettinger** 2016-08-11 13:17 UTC
