### ISSUE TITLE
NecroBot Not work

### ISSUE THREAD

**Issue by josevi88** [NECROBOTIO/NecroBot#5065] opened 2016-08-11 12:25 UTC
Hi all.

i have some problem with this bot.

look : http://prntscr.com/c4drxa

Bot just take one pokestop or caught 1-2 pokemon and stop , not work more.

yesterday work fine but today not.

Can somebody help me? thanks

**Comment by theloser** [comment] 2016-08-11 12:26
Did you use the search to check if there are similar issues? No.
Do it and you'll find a solution.

Plase close this issue, because it's a duplicate of a duplicate of a duplicate of ...

**Comment by josevi88** [comment] 2016-08-11 12:35
Pls tell me with is a problem and how can i solve it and close it

**Comment by thoramisu** [comment] 2016-08-11 12:36
Try changing the location in the conf.json file

**Comment by Georgiexoh** [comment] 2016-08-11 12:38
Im getting the same issue today, was working fine yesterday, but now only finds 1 stop then does nothing?

**Comment by theloser** [comment] 2016-08-11 12:39
@josevi88 Search the issues for "one pokestop", you'll find solutions/suggestions there.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions. Thanks!

**Comment by boomzbe** [comment] 2016-08-11 12:40
Causes pokezz snipe.


set it to false

**Comment by nfettinger** [comment] 2016-08-11 12:41
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.

**Closed by nfettinger** 2016-08-11 12:41 UTC
