### ISSUE TITLE
Razz Berry Usage

### ISSUE THREAD

**Issue by tiny1980** [NECROBOTIO/NecroBot#2576] opened 2016-08-03 16:46 UTC
Hello,

Since I seem to accumulate Razz Berries, I started to play with the settings to use them more often.  Watching the log though, I notice that when a Razz Berry is needed, it only uses it on the first throw.  tolerances aren't rechecked if there is an escape on subsequent throws.

*On a side note, I caught a 100% IV Vaporeon!  :)

```
[11:47:35] (BERRY) Used Razz Berry | 69 remaining
[11:47:36] (PKMN) (CatchEscape) | (Normal) Vaporeon Lvl: 21 CP: (1689/1689) IV:
100.00% | Chance: 9.8% | 16005714.83m dist | with a GreatBall (41 left). |  | la
t: -33.8597834836454 long: 151.216482426303
[11:47:39] (PKMN) (CatchSuccess Attempt #2) | (Normal) Vaporeon Lvl: 21 CP: (168
9/1689) IV: 100.00% | Chance: 9.8% | 16005714.83m dist | with a GreatBall (40 le
ft). | Candies: 151 | lat: -33.8597834836454 long: 151.216482426303
[11:47:46] (SNIPER) Sniping a Vaporeon with 204129 IV at 19.207578,-96.204129...

[11:47:48] (BERRY) Used Razz Berry | 68 remaining
[11:47:49] (PKMN) (CatchEscape) | (Normal) Vaporeon Lvl: 24 CP: (1913/1931) IV:
93.00% | Chance: 9.17% | 3199245.90m dist | with a GreatBall (39 left). |  | lat
: 19.2075781264505 long: -96.2041280160054
[11:47:51] (PKMN) (CatchEscape Attempt #2) | (Normal) Vaporeon Lvl: 24 CP: (1913
/1931) IV: 93.00% | Chance: 9.17% | 3199245.90m dist | with a GreatBall (38 left
). |  | lat: 19.2075781264505 long: -96.2041280160054
[11:47:54] (PKMN) (CatchEscape Attempt #3) | (Normal) Vaporeon Lvl: 24 CP: (1913
/1931) IV: 93.00% | Chance: 9.17% | 3199245.90m dist | with a GreatBall (37 left
). |  | lat: 19.2075781264505 long: -96.2041280160054
[11:47:56] (PKMN) (CatchEscape Attempt #4) | (Normal) Vaporeon Lvl: 24 CP: (1913
/1931) IV: 93.00% | Chance: 9.17% | 3199245.90m dist | with a GreatBall (36 left
). |  | lat: 19.2075781264505 long: -96.2041280160054
[11:47:59] (PKMN) (CatchEscape Attempt #5) | (Normal) Vaporeon Lvl: 24 CP: (1913
/1931) IV: 93.00% | Chance: 9.17% | 3199245.90m dist | with a GreatBall (35 left
). |  | lat: 19.2075781264505 long: -96.2041280160054
[11:48:02] (PKMN) (CatchSuccess Attempt #6) | (Normal) Vaporeon Lvl: 24 CP: (191
3/1931) IV: 93.00% | Chance: 9.17% | 3199245.90m dist | with a GreatBall (34 lef
t). | Candies: 154 | lat: 19.2075781264505 long: -96.2041280160054
```

**Comment by nfettinger** [comment] 2016-08-03 16:47
Duplicate of #2543

**Closed by nfettinger** 2016-08-03 16:47 UTC
