### ISSUE TITLE
Pokestops not found

### ISSUE THREAD

**Issue by Avitar** [NECROBOTIO/NecroBot#2690] opened 2016-08-03 21:30 UTC
I've tried adjusting the maximum distance to 500, 1000 (default), 1500, 2000, all the way up to 10,000. Same issue. No pokestops found. Tried logging out and logging back in. Tried using an older version but it auto-updated to the latest version. Currently using version v0.6.4. Using the normal Pokemon GO app works fine on my phone and pokestops and gyms can be interacted with.. but on the bot, no pokestops are found despite inputting the latitude and longitude (correct to 6 decimal places) in the /Config/config.json file of an area with 4 pokestops within 100m of each other.
http://s5.postimg.org/42qxi8vrb/screenshot_13.png
![screenshot_13](https://cloud.githubusercontent.com/assets/20825199/17382569/9314d574-599f-11e6-9df3-6b4a88f9d51d.png)

**Comment by JesusNoodl** [comment] 2016-08-03 21:30
#2645

**Comment by artuan00** [comment] 2016-08-03 21:31
#2645

**Comment by ferbeb** [comment] 2016-08-03 21:32
Just take a damn look at the issues page before posting a new one.

**Comment by DavidChristiansen** [comment] 2016-08-03 21:32
Please look and read existing issues before jumping in and creating your own :)

**Comment by lucasSykio** [comment] 2016-08-03 21:33
Before close it, any info about it expt "duplicated, closed" ?

**Comment by DavidChristiansen** [comment] 2016-08-03 21:34
Read the other issue for info

**Comment by tennosys** [comment] 2016-08-03 21:34
I think niantic patched the API, so every bot cant see pokestop and pokemon right now.

**Comment by lucasSykio** [comment] 2016-08-03 21:34
@DavidChristiansen Which one ?

**Comment by theloser** [comment] 2016-08-03 21:34
No pokestops found? Wow, that's something new!

No, obviously not: got to Issues, and use the Filter to search for **is:issue "no pokestop"** -- you will find 7 open and 46 closed issues. No need to open another one..

**Comment by DavidChristiansen** [comment] 2016-08-03 21:35
Troll? Issue #2645 <-- That is a link

**Comment by Avitar** [comment] 2016-08-03 21:35
I got an empty map object with an error from the API call. That's all I know.

**Comment by lucasSykio** [comment] 2016-08-03 21:37
@DavidChristiansen There is no info. Expt "Please wait patiently for an update." Thanks for your ans' :)
Troll ?

**Comment by Avitar** [comment] 2016-08-03 21:41
Guyz come on. Chill out. I didn't even know it had an issues page. I just found a bug and did my part to contribute by creating an account here and posting the information and screenshots i had. I'm new. Cut me some slack. Where's the issues page?

**Comment by nfettinger** [comment] 2016-08-03 21:42
Duplicate of #2645

**Comment by PewSztiePoll** [comment] 2016-08-03 21:42
@Avitar -> [Here it is](https://github.com/NECROBOTIO/NecroBot/issues)

**Closed** 2016-08-03 21:42 UTC

**Comment by theloser** [comment] 2016-08-03 21:52
@Avitar You managed to create an issue (this one you are reading right now!) without knowing about the issue page in first place? Wow!

I really appreciate that you want to contribute to the project, but please, to keep this clean, use the search (as you would in **every** other wiki/board/forum). Thanks!
